/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0041KillJobsMsg type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041KillJobsMsg{}

// V0041KillJobsMsg struct for V0041KillJobsMsg
type V0041KillJobsMsg struct {
	// Filter jobs to a specific account
	Account *string `json:"account,omitempty"`
	// Filter jobs according to flags
	Flags []string `json:"flags,omitempty"`
	// Filter jobs to a specific name
	JobName *string `json:"job_name,omitempty"`
	// List of jobs to signal
	Jobs []string `json:"jobs,omitempty"`
	// Filter jobs to a specific partition
	Partition *string `json:"partition,omitempty"`
	// Filter jobs to a specific QOS
	Qos *string `json:"qos,omitempty"`
	// Filter jobs to a specific reservation
	Reservation *string `json:"reservation,omitempty"`
	// Signal to send to jobs
	Signal *string `json:"signal,omitempty"`
	// Filter jobs to a specific state
	JobState []string `json:"job_state,omitempty"`
	// Filter jobs to a specific numeric user id
	UserId *string `json:"user_id,omitempty"`
	// Filter jobs to a specific user name
	UserName *string `json:"user_name,omitempty"`
	// Filter jobs to a specific wckey
	Wckey *string `json:"wckey,omitempty"`
	// Filter jobs to a set of nodes
	Nodes []string `json:"nodes,omitempty"`
}

// NewV0041KillJobsMsg instantiates a new V0041KillJobsMsg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041KillJobsMsg() *V0041KillJobsMsg {
	this := V0041KillJobsMsg{}
	return &this
}

// NewV0041KillJobsMsgWithDefaults instantiates a new V0041KillJobsMsg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041KillJobsMsgWithDefaults() *V0041KillJobsMsg {
	this := V0041KillJobsMsg{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetAccount() string {
	if o == nil || IsNil(o.Account) {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetAccountOk() (*string, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *V0041KillJobsMsg) SetAccount(v string) {
	o.Account = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetFlags() []string {
	if o == nil || IsNil(o.Flags) {
		var ret []string
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetFlagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *V0041KillJobsMsg) SetFlags(v []string) {
	o.Flags = v
}

// GetJobName returns the JobName field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetJobName() string {
	if o == nil || IsNil(o.JobName) {
		var ret string
		return ret
	}
	return *o.JobName
}

// GetJobNameOk returns a tuple with the JobName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetJobNameOk() (*string, bool) {
	if o == nil || IsNil(o.JobName) {
		return nil, false
	}
	return o.JobName, true
}

// HasJobName returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasJobName() bool {
	if o != nil && !IsNil(o.JobName) {
		return true
	}

	return false
}

// SetJobName gets a reference to the given string and assigns it to the JobName field.
func (o *V0041KillJobsMsg) SetJobName(v string) {
	o.JobName = &v
}

// GetJobs returns the Jobs field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetJobs() []string {
	if o == nil || IsNil(o.Jobs) {
		var ret []string
		return ret
	}
	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetJobsOk() ([]string, bool) {
	if o == nil || IsNil(o.Jobs) {
		return nil, false
	}
	return o.Jobs, true
}

// HasJobs returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasJobs() bool {
	if o != nil && !IsNil(o.Jobs) {
		return true
	}

	return false
}

// SetJobs gets a reference to the given []string and assigns it to the Jobs field.
func (o *V0041KillJobsMsg) SetJobs(v []string) {
	o.Jobs = v
}

// GetPartition returns the Partition field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetPartition() string {
	if o == nil || IsNil(o.Partition) {
		var ret string
		return ret
	}
	return *o.Partition
}

// GetPartitionOk returns a tuple with the Partition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetPartitionOk() (*string, bool) {
	if o == nil || IsNil(o.Partition) {
		return nil, false
	}
	return o.Partition, true
}

// HasPartition returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasPartition() bool {
	if o != nil && !IsNil(o.Partition) {
		return true
	}

	return false
}

// SetPartition gets a reference to the given string and assigns it to the Partition field.
func (o *V0041KillJobsMsg) SetPartition(v string) {
	o.Partition = &v
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetQos() string {
	if o == nil || IsNil(o.Qos) {
		var ret string
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetQosOk() (*string, bool) {
	if o == nil || IsNil(o.Qos) {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasQos() bool {
	if o != nil && !IsNil(o.Qos) {
		return true
	}

	return false
}

// SetQos gets a reference to the given string and assigns it to the Qos field.
func (o *V0041KillJobsMsg) SetQos(v string) {
	o.Qos = &v
}

// GetReservation returns the Reservation field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetReservation() string {
	if o == nil || IsNil(o.Reservation) {
		var ret string
		return ret
	}
	return *o.Reservation
}

// GetReservationOk returns a tuple with the Reservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetReservationOk() (*string, bool) {
	if o == nil || IsNil(o.Reservation) {
		return nil, false
	}
	return o.Reservation, true
}

// HasReservation returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasReservation() bool {
	if o != nil && !IsNil(o.Reservation) {
		return true
	}

	return false
}

// SetReservation gets a reference to the given string and assigns it to the Reservation field.
func (o *V0041KillJobsMsg) SetReservation(v string) {
	o.Reservation = &v
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetSignal() string {
	if o == nil || IsNil(o.Signal) {
		var ret string
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetSignalOk() (*string, bool) {
	if o == nil || IsNil(o.Signal) {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasSignal() bool {
	if o != nil && !IsNil(o.Signal) {
		return true
	}

	return false
}

// SetSignal gets a reference to the given string and assigns it to the Signal field.
func (o *V0041KillJobsMsg) SetSignal(v string) {
	o.Signal = &v
}

// GetJobState returns the JobState field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetJobState() []string {
	if o == nil || IsNil(o.JobState) {
		var ret []string
		return ret
	}
	return o.JobState
}

// GetJobStateOk returns a tuple with the JobState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetJobStateOk() ([]string, bool) {
	if o == nil || IsNil(o.JobState) {
		return nil, false
	}
	return o.JobState, true
}

// HasJobState returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasJobState() bool {
	if o != nil && !IsNil(o.JobState) {
		return true
	}

	return false
}

// SetJobState gets a reference to the given []string and assigns it to the JobState field.
func (o *V0041KillJobsMsg) SetJobState(v []string) {
	o.JobState = v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *V0041KillJobsMsg) SetUserId(v string) {
	o.UserId = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *V0041KillJobsMsg) SetUserName(v string) {
	o.UserName = &v
}

// GetWckey returns the Wckey field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetWckey() string {
	if o == nil || IsNil(o.Wckey) {
		var ret string
		return ret
	}
	return *o.Wckey
}

// GetWckeyOk returns a tuple with the Wckey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetWckeyOk() (*string, bool) {
	if o == nil || IsNil(o.Wckey) {
		return nil, false
	}
	return o.Wckey, true
}

// HasWckey returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasWckey() bool {
	if o != nil && !IsNil(o.Wckey) {
		return true
	}

	return false
}

// SetWckey gets a reference to the given string and assigns it to the Wckey field.
func (o *V0041KillJobsMsg) SetWckey(v string) {
	o.Wckey = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *V0041KillJobsMsg) GetNodes() []string {
	if o == nil || IsNil(o.Nodes) {
		var ret []string
		return ret
	}
	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041KillJobsMsg) GetNodesOk() ([]string, bool) {
	if o == nil || IsNil(o.Nodes) {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *V0041KillJobsMsg) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given []string and assigns it to the Nodes field.
func (o *V0041KillJobsMsg) SetNodes(v []string) {
	o.Nodes = v
}

func (o V0041KillJobsMsg) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041KillJobsMsg) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.JobName) {
		toSerialize["job_name"] = o.JobName
	}
	if !IsNil(o.Jobs) {
		toSerialize["jobs"] = o.Jobs
	}
	if !IsNil(o.Partition) {
		toSerialize["partition"] = o.Partition
	}
	if !IsNil(o.Qos) {
		toSerialize["qos"] = o.Qos
	}
	if !IsNil(o.Reservation) {
		toSerialize["reservation"] = o.Reservation
	}
	if !IsNil(o.Signal) {
		toSerialize["signal"] = o.Signal
	}
	if !IsNil(o.JobState) {
		toSerialize["job_state"] = o.JobState
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.UserName) {
		toSerialize["user_name"] = o.UserName
	}
	if !IsNil(o.Wckey) {
		toSerialize["wckey"] = o.Wckey
	}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	return toSerialize, nil
}

type NullableV0041KillJobsMsg struct {
	value *V0041KillJobsMsg
	isSet bool
}

func (v NullableV0041KillJobsMsg) Get() *V0041KillJobsMsg {
	return v.value
}

func (v *NullableV0041KillJobsMsg) Set(val *V0041KillJobsMsg) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041KillJobsMsg) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041KillJobsMsg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041KillJobsMsg(val *V0041KillJobsMsg) *NullableV0041KillJobsMsg {
	return &NullableV0041KillJobsMsg{value: val, isSet: true}
}

func (v NullableV0041KillJobsMsg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041KillJobsMsg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


