/*
Slurm Rest API

API to access and control Slurm.

API version: Slurm-23.11.1&openapi/v0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi&openapi/dbv0.0.39
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0039QosLimitsMin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0039QosLimitsMin{}

// V0039QosLimitsMin struct for V0039QosLimitsMin
type V0039QosLimitsMin struct {
	PriorityThreshold *V0039Uint32NoVal `json:"priority_threshold,omitempty"`
	Tres *V0039QosLimitsMinTres `json:"tres,omitempty"`
}

// NewV0039QosLimitsMin instantiates a new V0039QosLimitsMin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0039QosLimitsMin() *V0039QosLimitsMin {
	this := V0039QosLimitsMin{}
	return &this
}

// NewV0039QosLimitsMinWithDefaults instantiates a new V0039QosLimitsMin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0039QosLimitsMinWithDefaults() *V0039QosLimitsMin {
	this := V0039QosLimitsMin{}
	return &this
}

// GetPriorityThreshold returns the PriorityThreshold field value if set, zero value otherwise.
func (o *V0039QosLimitsMin) GetPriorityThreshold() V0039Uint32NoVal {
	if o == nil || IsNil(o.PriorityThreshold) {
		var ret V0039Uint32NoVal
		return ret
	}
	return *o.PriorityThreshold
}

// GetPriorityThresholdOk returns a tuple with the PriorityThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0039QosLimitsMin) GetPriorityThresholdOk() (*V0039Uint32NoVal, bool) {
	if o == nil || IsNil(o.PriorityThreshold) {
		return nil, false
	}
	return o.PriorityThreshold, true
}

// HasPriorityThreshold returns a boolean if a field has been set.
func (o *V0039QosLimitsMin) HasPriorityThreshold() bool {
	if o != nil && !IsNil(o.PriorityThreshold) {
		return true
	}

	return false
}

// SetPriorityThreshold gets a reference to the given V0039Uint32NoVal and assigns it to the PriorityThreshold field.
func (o *V0039QosLimitsMin) SetPriorityThreshold(v V0039Uint32NoVal) {
	o.PriorityThreshold = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0039QosLimitsMin) GetTres() V0039QosLimitsMinTres {
	if o == nil || IsNil(o.Tres) {
		var ret V0039QosLimitsMinTres
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0039QosLimitsMin) GetTresOk() (*V0039QosLimitsMinTres, bool) {
	if o == nil || IsNil(o.Tres) {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0039QosLimitsMin) HasTres() bool {
	if o != nil && !IsNil(o.Tres) {
		return true
	}

	return false
}

// SetTres gets a reference to the given V0039QosLimitsMinTres and assigns it to the Tres field.
func (o *V0039QosLimitsMin) SetTres(v V0039QosLimitsMinTres) {
	o.Tres = &v
}

func (o V0039QosLimitsMin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0039QosLimitsMin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PriorityThreshold) {
		toSerialize["priority_threshold"] = o.PriorityThreshold
	}
	if !IsNil(o.Tres) {
		toSerialize["tres"] = o.Tres
	}
	return toSerialize, nil
}

type NullableV0039QosLimitsMin struct {
	value *V0039QosLimitsMin
	isSet bool
}

func (v NullableV0039QosLimitsMin) Get() *V0039QosLimitsMin {
	return v.value
}

func (v *NullableV0039QosLimitsMin) Set(val *V0039QosLimitsMin) {
	v.value = val
	v.isSet = true
}

func (v NullableV0039QosLimitsMin) IsSet() bool {
	return v.isSet
}

func (v *NullableV0039QosLimitsMin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0039QosLimitsMin(val *V0039QosLimitsMin) *NullableV0039QosLimitsMin {
	return &NullableV0039QosLimitsMin{value: val, isSet: true}
}

func (v NullableV0039QosLimitsMin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0039QosLimitsMin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


