/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.11.4&openapi/slurmctld&openapi/slurmdbd
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0041OpenapiNodesRespNodesInnerEnergy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiNodesRespNodesInnerEnergy{}

// V0041OpenapiNodesRespNodesInnerEnergy Energy usage data
type V0041OpenapiNodesRespNodesInnerEnergy struct {
	// Average power consumption, in watts
	AverageWatts *int32 `json:"average_watts,omitempty"`
	// The energy consumed between when the node was powered on and the last time it was registered by slurmd, in joules
	BaseConsumedEnergy *int64 `json:"base_consumed_energy,omitempty"`
	// The energy consumed between the last time the node was registered by the slurmd daemon and the last node energy accounting sample, in joules
	ConsumedEnergy *int64 `json:"consumed_energy,omitempty"`
	CurrentWatts *V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts `json:"current_watts,omitempty"`
	// Previous value of consumed_energy
	PreviousConsumedEnergy *int64 `json:"previous_consumed_energy,omitempty"`
	// Time when energy data was last retrieved (UNIX timestamp)
	LastCollected *int64 `json:"last_collected,omitempty"`
}

// NewV0041OpenapiNodesRespNodesInnerEnergy instantiates a new V0041OpenapiNodesRespNodesInnerEnergy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiNodesRespNodesInnerEnergy() *V0041OpenapiNodesRespNodesInnerEnergy {
	this := V0041OpenapiNodesRespNodesInnerEnergy{}
	return &this
}

// NewV0041OpenapiNodesRespNodesInnerEnergyWithDefaults instantiates a new V0041OpenapiNodesRespNodesInnerEnergy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiNodesRespNodesInnerEnergyWithDefaults() *V0041OpenapiNodesRespNodesInnerEnergy {
	this := V0041OpenapiNodesRespNodesInnerEnergy{}
	return &this
}

// GetAverageWatts returns the AverageWatts field value if set, zero value otherwise.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetAverageWatts() int32 {
	if o == nil || IsNil(o.AverageWatts) {
		var ret int32
		return ret
	}
	return *o.AverageWatts
}

// GetAverageWattsOk returns a tuple with the AverageWatts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetAverageWattsOk() (*int32, bool) {
	if o == nil || IsNil(o.AverageWatts) {
		return nil, false
	}
	return o.AverageWatts, true
}

// HasAverageWatts returns a boolean if a field has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) HasAverageWatts() bool {
	if o != nil && !IsNil(o.AverageWatts) {
		return true
	}

	return false
}

// SetAverageWatts gets a reference to the given int32 and assigns it to the AverageWatts field.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) SetAverageWatts(v int32) {
	o.AverageWatts = &v
}

// GetBaseConsumedEnergy returns the BaseConsumedEnergy field value if set, zero value otherwise.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetBaseConsumedEnergy() int64 {
	if o == nil || IsNil(o.BaseConsumedEnergy) {
		var ret int64
		return ret
	}
	return *o.BaseConsumedEnergy
}

// GetBaseConsumedEnergyOk returns a tuple with the BaseConsumedEnergy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetBaseConsumedEnergyOk() (*int64, bool) {
	if o == nil || IsNil(o.BaseConsumedEnergy) {
		return nil, false
	}
	return o.BaseConsumedEnergy, true
}

// HasBaseConsumedEnergy returns a boolean if a field has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) HasBaseConsumedEnergy() bool {
	if o != nil && !IsNil(o.BaseConsumedEnergy) {
		return true
	}

	return false
}

// SetBaseConsumedEnergy gets a reference to the given int64 and assigns it to the BaseConsumedEnergy field.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) SetBaseConsumedEnergy(v int64) {
	o.BaseConsumedEnergy = &v
}

// GetConsumedEnergy returns the ConsumedEnergy field value if set, zero value otherwise.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetConsumedEnergy() int64 {
	if o == nil || IsNil(o.ConsumedEnergy) {
		var ret int64
		return ret
	}
	return *o.ConsumedEnergy
}

// GetConsumedEnergyOk returns a tuple with the ConsumedEnergy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetConsumedEnergyOk() (*int64, bool) {
	if o == nil || IsNil(o.ConsumedEnergy) {
		return nil, false
	}
	return o.ConsumedEnergy, true
}

// HasConsumedEnergy returns a boolean if a field has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) HasConsumedEnergy() bool {
	if o != nil && !IsNil(o.ConsumedEnergy) {
		return true
	}

	return false
}

// SetConsumedEnergy gets a reference to the given int64 and assigns it to the ConsumedEnergy field.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) SetConsumedEnergy(v int64) {
	o.ConsumedEnergy = &v
}

// GetCurrentWatts returns the CurrentWatts field value if set, zero value otherwise.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetCurrentWatts() V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts {
	if o == nil || IsNil(o.CurrentWatts) {
		var ret V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts
		return ret
	}
	return *o.CurrentWatts
}

// GetCurrentWattsOk returns a tuple with the CurrentWatts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetCurrentWattsOk() (*V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts, bool) {
	if o == nil || IsNil(o.CurrentWatts) {
		return nil, false
	}
	return o.CurrentWatts, true
}

// HasCurrentWatts returns a boolean if a field has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) HasCurrentWatts() bool {
	if o != nil && !IsNil(o.CurrentWatts) {
		return true
	}

	return false
}

// SetCurrentWatts gets a reference to the given V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts and assigns it to the CurrentWatts field.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) SetCurrentWatts(v V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts) {
	o.CurrentWatts = &v
}

// GetPreviousConsumedEnergy returns the PreviousConsumedEnergy field value if set, zero value otherwise.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetPreviousConsumedEnergy() int64 {
	if o == nil || IsNil(o.PreviousConsumedEnergy) {
		var ret int64
		return ret
	}
	return *o.PreviousConsumedEnergy
}

// GetPreviousConsumedEnergyOk returns a tuple with the PreviousConsumedEnergy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetPreviousConsumedEnergyOk() (*int64, bool) {
	if o == nil || IsNil(o.PreviousConsumedEnergy) {
		return nil, false
	}
	return o.PreviousConsumedEnergy, true
}

// HasPreviousConsumedEnergy returns a boolean if a field has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) HasPreviousConsumedEnergy() bool {
	if o != nil && !IsNil(o.PreviousConsumedEnergy) {
		return true
	}

	return false
}

// SetPreviousConsumedEnergy gets a reference to the given int64 and assigns it to the PreviousConsumedEnergy field.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) SetPreviousConsumedEnergy(v int64) {
	o.PreviousConsumedEnergy = &v
}

// GetLastCollected returns the LastCollected field value if set, zero value otherwise.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetLastCollected() int64 {
	if o == nil || IsNil(o.LastCollected) {
		var ret int64
		return ret
	}
	return *o.LastCollected
}

// GetLastCollectedOk returns a tuple with the LastCollected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) GetLastCollectedOk() (*int64, bool) {
	if o == nil || IsNil(o.LastCollected) {
		return nil, false
	}
	return o.LastCollected, true
}

// HasLastCollected returns a boolean if a field has been set.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) HasLastCollected() bool {
	if o != nil && !IsNil(o.LastCollected) {
		return true
	}

	return false
}

// SetLastCollected gets a reference to the given int64 and assigns it to the LastCollected field.
func (o *V0041OpenapiNodesRespNodesInnerEnergy) SetLastCollected(v int64) {
	o.LastCollected = &v
}

func (o V0041OpenapiNodesRespNodesInnerEnergy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiNodesRespNodesInnerEnergy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AverageWatts) {
		toSerialize["average_watts"] = o.AverageWatts
	}
	if !IsNil(o.BaseConsumedEnergy) {
		toSerialize["base_consumed_energy"] = o.BaseConsumedEnergy
	}
	if !IsNil(o.ConsumedEnergy) {
		toSerialize["consumed_energy"] = o.ConsumedEnergy
	}
	if !IsNil(o.CurrentWatts) {
		toSerialize["current_watts"] = o.CurrentWatts
	}
	if !IsNil(o.PreviousConsumedEnergy) {
		toSerialize["previous_consumed_energy"] = o.PreviousConsumedEnergy
	}
	if !IsNil(o.LastCollected) {
		toSerialize["last_collected"] = o.LastCollected
	}
	return toSerialize, nil
}

type NullableV0041OpenapiNodesRespNodesInnerEnergy struct {
	value *V0041OpenapiNodesRespNodesInnerEnergy
	isSet bool
}

func (v NullableV0041OpenapiNodesRespNodesInnerEnergy) Get() *V0041OpenapiNodesRespNodesInnerEnergy {
	return v.value
}

func (v *NullableV0041OpenapiNodesRespNodesInnerEnergy) Set(val *V0041OpenapiNodesRespNodesInnerEnergy) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiNodesRespNodesInnerEnergy) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiNodesRespNodesInnerEnergy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiNodesRespNodesInnerEnergy(val *V0041OpenapiNodesRespNodesInnerEnergy) *NullableV0041OpenapiNodesRespNodesInnerEnergy {
	return &NullableV0041OpenapiNodesRespNodesInnerEnergy{value: val, isSet: true}
}

func (v NullableV0041OpenapiNodesRespNodesInnerEnergy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiNodesRespNodesInnerEnergy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


