/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.11.4&openapi/slurmctld&openapi/slurmdbd
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0042PartitionInfoPartition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0042PartitionInfoPartition{}

// V0042PartitionInfoPartition struct for V0042PartitionInfoPartition
type V0042PartitionInfoPartition struct {
	State []string `json:"state,omitempty"`
}

// NewV0042PartitionInfoPartition instantiates a new V0042PartitionInfoPartition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042PartitionInfoPartition() *V0042PartitionInfoPartition {
	this := V0042PartitionInfoPartition{}
	return &this
}

// NewV0042PartitionInfoPartitionWithDefaults instantiates a new V0042PartitionInfoPartition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042PartitionInfoPartitionWithDefaults() *V0042PartitionInfoPartition {
	this := V0042PartitionInfoPartition{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V0042PartitionInfoPartition) GetState() []string {
	if o == nil || IsNil(o.State) {
		var ret []string
		return ret
	}
	return o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042PartitionInfoPartition) GetStateOk() ([]string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V0042PartitionInfoPartition) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given []string and assigns it to the State field.
func (o *V0042PartitionInfoPartition) SetState(v []string) {
	o.State = v
}

func (o V0042PartitionInfoPartition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0042PartitionInfoPartition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableV0042PartitionInfoPartition struct {
	value *V0042PartitionInfoPartition
	isSet bool
}

func (v NullableV0042PartitionInfoPartition) Get() *V0042PartitionInfoPartition {
	return v.value
}

func (v *NullableV0042PartitionInfoPartition) Set(val *V0042PartitionInfoPartition) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042PartitionInfoPartition) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042PartitionInfoPartition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042PartitionInfoPartition(val *V0042PartitionInfoPartition) *NullableV0042PartitionInfoPartition {
	return &NullableV0042PartitionInfoPartition{value: val, isSet: true}
}

func (v NullableV0042PartitionInfoPartition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042PartitionInfoPartition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


