/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory{}

// V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory struct for V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory
type V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory struct {
	// Total memory (MiB) used by job
	Used *int64 `json:"used,omitempty"`
	// Total memory (MiB) allocated to job
	Allocated *int64 `json:"allocated,omitempty"`
}

// NewV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory instantiates a new V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory() *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory {
	this := V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory{}
	return &this
}

// NewV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemoryWithDefaults instantiates a new V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemoryWithDefaults() *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory {
	this := V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory{}
	return &this
}

// GetUsed returns the Used field value if set, zero value otherwise.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) GetUsed() int64 {
	if o == nil || IsNil(o.Used) {
		var ret int64
		return ret
	}
	return *o.Used
}

// GetUsedOk returns a tuple with the Used field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) GetUsedOk() (*int64, bool) {
	if o == nil || IsNil(o.Used) {
		return nil, false
	}
	return o.Used, true
}

// HasUsed returns a boolean if a field has been set.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) HasUsed() bool {
	if o != nil && !IsNil(o.Used) {
		return true
	}

	return false
}

// SetUsed gets a reference to the given int64 and assigns it to the Used field.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) SetUsed(v int64) {
	o.Used = &v
}

// GetAllocated returns the Allocated field value if set, zero value otherwise.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) GetAllocated() int64 {
	if o == nil || IsNil(o.Allocated) {
		var ret int64
		return ret
	}
	return *o.Allocated
}

// GetAllocatedOk returns a tuple with the Allocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) GetAllocatedOk() (*int64, bool) {
	if o == nil || IsNil(o.Allocated) {
		return nil, false
	}
	return o.Allocated, true
}

// HasAllocated returns a boolean if a field has been set.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) HasAllocated() bool {
	if o != nil && !IsNil(o.Allocated) {
		return true
	}

	return false
}

// SetAllocated gets a reference to the given int64 and assigns it to the Allocated field.
func (o *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) SetAllocated(v int64) {
	o.Allocated = &v
}

func (o V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Used) {
		toSerialize["used"] = o.Used
	}
	if !IsNil(o.Allocated) {
		toSerialize["allocated"] = o.Allocated
	}
	return toSerialize, nil
}

type NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory struct {
	value *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory
	isSet bool
}

func (v NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) Get() *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory {
	return v.value
}

func (v *NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) Set(val *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory(val *V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) *NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory {
	return &NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory{value: val, isSet: true}
}

func (v NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


