/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0041OpenapiSharesRespWarningsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiSharesRespWarningsInner{}

// V0041OpenapiSharesRespWarningsInner struct for V0041OpenapiSharesRespWarningsInner
type V0041OpenapiSharesRespWarningsInner struct {
	// Long form warning description
	Description *string `json:"description,omitempty"`
	// Source of warning or where warning was first detected
	Source *string `json:"source,omitempty"`
}

// NewV0041OpenapiSharesRespWarningsInner instantiates a new V0041OpenapiSharesRespWarningsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSharesRespWarningsInner() *V0041OpenapiSharesRespWarningsInner {
	this := V0041OpenapiSharesRespWarningsInner{}
	return &this
}

// NewV0041OpenapiSharesRespWarningsInnerWithDefaults instantiates a new V0041OpenapiSharesRespWarningsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSharesRespWarningsInnerWithDefaults() *V0041OpenapiSharesRespWarningsInner {
	this := V0041OpenapiSharesRespWarningsInner{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *V0041OpenapiSharesRespWarningsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSharesRespWarningsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *V0041OpenapiSharesRespWarningsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *V0041OpenapiSharesRespWarningsInner) SetDescription(v string) {
	o.Description = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *V0041OpenapiSharesRespWarningsInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSharesRespWarningsInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *V0041OpenapiSharesRespWarningsInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *V0041OpenapiSharesRespWarningsInner) SetSource(v string) {
	o.Source = &v
}

func (o V0041OpenapiSharesRespWarningsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiSharesRespWarningsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableV0041OpenapiSharesRespWarningsInner struct {
	value *V0041OpenapiSharesRespWarningsInner
	isSet bool
}

func (v NullableV0041OpenapiSharesRespWarningsInner) Get() *V0041OpenapiSharesRespWarningsInner {
	return v.value
}

func (v *NullableV0041OpenapiSharesRespWarningsInner) Set(val *V0041OpenapiSharesRespWarningsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSharesRespWarningsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSharesRespWarningsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSharesRespWarningsInner(val *V0041OpenapiSharesRespWarningsInner) *NullableV0041OpenapiSharesRespWarningsInner {
	return &NullableV0041OpenapiSharesRespWarningsInner{value: val, isSet: true}
}

func (v NullableV0041OpenapiSharesRespWarningsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSharesRespWarningsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


