/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V0041OpenapiUsersResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiUsersResp{}

// V0041OpenapiUsersResp struct for V0041OpenapiUsersResp
type V0041OpenapiUsersResp struct {
	// users
	Users []V0041OpenapiSlurmdbdConfigRespUsersInner `json:"users"`
	Meta *V0041OpenapiSharesRespMeta `json:"meta,omitempty"`
	// Query errors
	Errors []V0041OpenapiSharesRespErrorsInner `json:"errors,omitempty"`
	// Query warnings
	Warnings []V0041OpenapiSharesRespWarningsInner `json:"warnings,omitempty"`
}

type _V0041OpenapiUsersResp V0041OpenapiUsersResp

// NewV0041OpenapiUsersResp instantiates a new V0041OpenapiUsersResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiUsersResp(users []V0041OpenapiSlurmdbdConfigRespUsersInner) *V0041OpenapiUsersResp {
	this := V0041OpenapiUsersResp{}
	this.Users = users
	return &this
}

// NewV0041OpenapiUsersRespWithDefaults instantiates a new V0041OpenapiUsersResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiUsersRespWithDefaults() *V0041OpenapiUsersResp {
	this := V0041OpenapiUsersResp{}
	return &this
}

// GetUsers returns the Users field value
func (o *V0041OpenapiUsersResp) GetUsers() []V0041OpenapiSlurmdbdConfigRespUsersInner {
	if o == nil {
		var ret []V0041OpenapiSlurmdbdConfigRespUsersInner
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *V0041OpenapiUsersResp) GetUsersOk() ([]V0041OpenapiSlurmdbdConfigRespUsersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *V0041OpenapiUsersResp) SetUsers(v []V0041OpenapiSlurmdbdConfigRespUsersInner) {
	o.Users = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0041OpenapiUsersResp) GetMeta() V0041OpenapiSharesRespMeta {
	if o == nil || IsNil(o.Meta) {
		var ret V0041OpenapiSharesRespMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiUsersResp) GetMetaOk() (*V0041OpenapiSharesRespMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0041OpenapiUsersResp) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0041OpenapiSharesRespMeta and assigns it to the Meta field.
func (o *V0041OpenapiUsersResp) SetMeta(v V0041OpenapiSharesRespMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0041OpenapiUsersResp) GetErrors() []V0041OpenapiSharesRespErrorsInner {
	if o == nil || IsNil(o.Errors) {
		var ret []V0041OpenapiSharesRespErrorsInner
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiUsersResp) GetErrorsOk() ([]V0041OpenapiSharesRespErrorsInner, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0041OpenapiUsersResp) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0041OpenapiSharesRespErrorsInner and assigns it to the Errors field.
func (o *V0041OpenapiUsersResp) SetErrors(v []V0041OpenapiSharesRespErrorsInner) {
	o.Errors = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0041OpenapiUsersResp) GetWarnings() []V0041OpenapiSharesRespWarningsInner {
	if o == nil || IsNil(o.Warnings) {
		var ret []V0041OpenapiSharesRespWarningsInner
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiUsersResp) GetWarningsOk() ([]V0041OpenapiSharesRespWarningsInner, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0041OpenapiUsersResp) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0041OpenapiSharesRespWarningsInner and assigns it to the Warnings field.
func (o *V0041OpenapiUsersResp) SetWarnings(v []V0041OpenapiSharesRespWarningsInner) {
	o.Warnings = v
}

func (o V0041OpenapiUsersResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiUsersResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *V0041OpenapiUsersResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"users",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV0041OpenapiUsersResp := _V0041OpenapiUsersResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV0041OpenapiUsersResp)

	if err != nil {
		return err
	}

	*o = V0041OpenapiUsersResp(varV0041OpenapiUsersResp)

	return err
}

type NullableV0041OpenapiUsersResp struct {
	value *V0041OpenapiUsersResp
	isSet bool
}

func (v NullableV0041OpenapiUsersResp) Get() *V0041OpenapiUsersResp {
	return v.value
}

func (v *NullableV0041OpenapiUsersResp) Set(val *V0041OpenapiUsersResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiUsersResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiUsersResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiUsersResp(val *V0041OpenapiUsersResp) *NullableV0041OpenapiUsersResp {
	return &NullableV0041OpenapiUsersResp{value: val, isSet: true}
}

func (v NullableV0041OpenapiUsersResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiUsersResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


