/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V0044OpenapiPartitionResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044OpenapiPartitionResp{}

// V0044OpenapiPartitionResp struct for V0044OpenapiPartitionResp
type V0044OpenapiPartitionResp struct {
	Partitions []V0044PartitionInfo `json:"partitions"`
	LastUpdate V0044Uint64NoValStruct `json:"last_update"`
	Meta *V0044OpenapiMeta `json:"meta,omitempty"`
	Errors []V0044OpenapiError `json:"errors,omitempty"`
	Warnings []V0044OpenapiWarning `json:"warnings,omitempty"`
}

type _V0044OpenapiPartitionResp V0044OpenapiPartitionResp

// NewV0044OpenapiPartitionResp instantiates a new V0044OpenapiPartitionResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044OpenapiPartitionResp(partitions []V0044PartitionInfo, lastUpdate V0044Uint64NoValStruct) *V0044OpenapiPartitionResp {
	this := V0044OpenapiPartitionResp{}
	this.Partitions = partitions
	this.LastUpdate = lastUpdate
	return &this
}

// NewV0044OpenapiPartitionRespWithDefaults instantiates a new V0044OpenapiPartitionResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044OpenapiPartitionRespWithDefaults() *V0044OpenapiPartitionResp {
	this := V0044OpenapiPartitionResp{}
	return &this
}

// GetPartitions returns the Partitions field value
func (o *V0044OpenapiPartitionResp) GetPartitions() []V0044PartitionInfo {
	if o == nil {
		var ret []V0044PartitionInfo
		return ret
	}

	return o.Partitions
}

// GetPartitionsOk returns a tuple with the Partitions field value
// and a boolean to check if the value has been set.
func (o *V0044OpenapiPartitionResp) GetPartitionsOk() ([]V0044PartitionInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Partitions, true
}

// SetPartitions sets field value
func (o *V0044OpenapiPartitionResp) SetPartitions(v []V0044PartitionInfo) {
	o.Partitions = v
}

// GetLastUpdate returns the LastUpdate field value
func (o *V0044OpenapiPartitionResp) GetLastUpdate() V0044Uint64NoValStruct {
	if o == nil {
		var ret V0044Uint64NoValStruct
		return ret
	}

	return o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value
// and a boolean to check if the value has been set.
func (o *V0044OpenapiPartitionResp) GetLastUpdateOk() (*V0044Uint64NoValStruct, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdate, true
}

// SetLastUpdate sets field value
func (o *V0044OpenapiPartitionResp) SetLastUpdate(v V0044Uint64NoValStruct) {
	o.LastUpdate = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0044OpenapiPartitionResp) GetMeta() V0044OpenapiMeta {
	if o == nil || IsNil(o.Meta) {
		var ret V0044OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiPartitionResp) GetMetaOk() (*V0044OpenapiMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0044OpenapiPartitionResp) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0044OpenapiMeta and assigns it to the Meta field.
func (o *V0044OpenapiPartitionResp) SetMeta(v V0044OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0044OpenapiPartitionResp) GetErrors() []V0044OpenapiError {
	if o == nil || IsNil(o.Errors) {
		var ret []V0044OpenapiError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiPartitionResp) GetErrorsOk() ([]V0044OpenapiError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0044OpenapiPartitionResp) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0044OpenapiError and assigns it to the Errors field.
func (o *V0044OpenapiPartitionResp) SetErrors(v []V0044OpenapiError) {
	o.Errors = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0044OpenapiPartitionResp) GetWarnings() []V0044OpenapiWarning {
	if o == nil || IsNil(o.Warnings) {
		var ret []V0044OpenapiWarning
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiPartitionResp) GetWarningsOk() ([]V0044OpenapiWarning, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0044OpenapiPartitionResp) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0044OpenapiWarning and assigns it to the Warnings field.
func (o *V0044OpenapiPartitionResp) SetWarnings(v []V0044OpenapiWarning) {
	o.Warnings = v
}

func (o V0044OpenapiPartitionResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044OpenapiPartitionResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["partitions"] = o.Partitions
	toSerialize["last_update"] = o.LastUpdate
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *V0044OpenapiPartitionResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"partitions",
		"last_update",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV0044OpenapiPartitionResp := _V0044OpenapiPartitionResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV0044OpenapiPartitionResp)

	if err != nil {
		return err
	}

	*o = V0044OpenapiPartitionResp(varV0044OpenapiPartitionResp)

	return err
}

type NullableV0044OpenapiPartitionResp struct {
	value *V0044OpenapiPartitionResp
	isSet bool
}

func (v NullableV0044OpenapiPartitionResp) Get() *V0044OpenapiPartitionResp {
	return v.value
}

func (v *NullableV0044OpenapiPartitionResp) Set(val *V0044OpenapiPartitionResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044OpenapiPartitionResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044OpenapiPartitionResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044OpenapiPartitionResp(val *V0044OpenapiPartitionResp) *NullableV0044OpenapiPartitionResp {
	return &NullableV0044OpenapiPartitionResp{value: val, isSet: true}
}

func (v NullableV0044OpenapiPartitionResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044OpenapiPartitionResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


