/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V0043AccountsAddCond type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0043AccountsAddCond{}

// V0043AccountsAddCond struct for V0043AccountsAddCond
type V0043AccountsAddCond struct {
	Accounts []string `json:"accounts"`
	Association *V0043AssocRecSet `json:"association,omitempty"`
	Clusters []string `json:"clusters,omitempty"`
}

type _V0043AccountsAddCond V0043AccountsAddCond

// NewV0043AccountsAddCond instantiates a new V0043AccountsAddCond object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043AccountsAddCond(accounts []string) *V0043AccountsAddCond {
	this := V0043AccountsAddCond{}
	this.Accounts = accounts
	return &this
}

// NewV0043AccountsAddCondWithDefaults instantiates a new V0043AccountsAddCond object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043AccountsAddCondWithDefaults() *V0043AccountsAddCond {
	this := V0043AccountsAddCond{}
	return &this
}

// GetAccounts returns the Accounts field value
func (o *V0043AccountsAddCond) GetAccounts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *V0043AccountsAddCond) GetAccountsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *V0043AccountsAddCond) SetAccounts(v []string) {
	o.Accounts = v
}

// GetAssociation returns the Association field value if set, zero value otherwise.
func (o *V0043AccountsAddCond) GetAssociation() V0043AssocRecSet {
	if o == nil || IsNil(o.Association) {
		var ret V0043AssocRecSet
		return ret
	}
	return *o.Association
}

// GetAssociationOk returns a tuple with the Association field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AccountsAddCond) GetAssociationOk() (*V0043AssocRecSet, bool) {
	if o == nil || IsNil(o.Association) {
		return nil, false
	}
	return o.Association, true
}

// HasAssociation returns a boolean if a field has been set.
func (o *V0043AccountsAddCond) HasAssociation() bool {
	if o != nil && !IsNil(o.Association) {
		return true
	}

	return false
}

// SetAssociation gets a reference to the given V0043AssocRecSet and assigns it to the Association field.
func (o *V0043AccountsAddCond) SetAssociation(v V0043AssocRecSet) {
	o.Association = &v
}

// GetClusters returns the Clusters field value if set, zero value otherwise.
func (o *V0043AccountsAddCond) GetClusters() []string {
	if o == nil || IsNil(o.Clusters) {
		var ret []string
		return ret
	}
	return o.Clusters
}

// GetClustersOk returns a tuple with the Clusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AccountsAddCond) GetClustersOk() ([]string, bool) {
	if o == nil || IsNil(o.Clusters) {
		return nil, false
	}
	return o.Clusters, true
}

// HasClusters returns a boolean if a field has been set.
func (o *V0043AccountsAddCond) HasClusters() bool {
	if o != nil && !IsNil(o.Clusters) {
		return true
	}

	return false
}

// SetClusters gets a reference to the given []string and assigns it to the Clusters field.
func (o *V0043AccountsAddCond) SetClusters(v []string) {
	o.Clusters = v
}

func (o V0043AccountsAddCond) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0043AccountsAddCond) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounts"] = o.Accounts
	if !IsNil(o.Association) {
		toSerialize["association"] = o.Association
	}
	if !IsNil(o.Clusters) {
		toSerialize["clusters"] = o.Clusters
	}
	return toSerialize, nil
}

func (o *V0043AccountsAddCond) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accounts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV0043AccountsAddCond := _V0043AccountsAddCond{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV0043AccountsAddCond)

	if err != nil {
		return err
	}

	*o = V0043AccountsAddCond(varV0043AccountsAddCond)

	return err
}

type NullableV0043AccountsAddCond struct {
	value *V0043AccountsAddCond
	isSet bool
}

func (v NullableV0043AccountsAddCond) Get() *V0043AccountsAddCond {
	return v.value
}

func (v *NullableV0043AccountsAddCond) Set(val *V0043AccountsAddCond) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043AccountsAddCond) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043AccountsAddCond) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043AccountsAddCond(val *V0043AccountsAddCond) *NullableV0043AccountsAddCond {
	return &NullableV0043AccountsAddCond{value: val, isSet: true}
}

func (v NullableV0043AccountsAddCond) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043AccountsAddCond) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


