/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the SlurmV0041GetShares200ResponseSharesSharesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmV0041GetShares200ResponseSharesSharesInner{}

// SlurmV0041GetShares200ResponseSharesSharesInner struct for SlurmV0041GetShares200ResponseSharesSharesInner
type SlurmV0041GetShares200ResponseSharesSharesInner struct {
	// Association ID
	Id *int32 `json:"id,omitempty"`
	// Cluster name
	Cluster *string `json:"cluster,omitempty"`
	// Share name
	Name *string `json:"name,omitempty"`
	// Parent name
	Parent *string `json:"parent,omitempty"`
	// Partition name
	Partition *string `json:"partition,omitempty"`
	SharesNormalized *SlurmV0041GetShares200ResponseSharesSharesInnerSharesNormalized `json:"shares_normalized,omitempty"`
	Shares *SlurmV0041GetShares200ResponseSharesSharesInnerShares `json:"shares,omitempty"`
	Tres *SlurmV0041GetShares200ResponseSharesSharesInnerTres `json:"tres,omitempty"`
	// Effective, normalized usage
	EffectiveUsage *float64 `json:"effective_usage,omitempty"`
	UsageNormalized *SlurmV0041GetShares200ResponseSharesSharesInnerUsageNormalized `json:"usage_normalized,omitempty"`
	// Measure of tresbillableunits usage
	Usage *int64 `json:"usage,omitempty"`
	Fairshare *SlurmV0041GetShares200ResponseSharesSharesInnerFairshare `json:"fairshare,omitempty"`
	// User or account association
	Type []string `json:"type,omitempty"`
}

// NewSlurmV0041GetShares200ResponseSharesSharesInner instantiates a new SlurmV0041GetShares200ResponseSharesSharesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmV0041GetShares200ResponseSharesSharesInner() *SlurmV0041GetShares200ResponseSharesSharesInner {
	this := SlurmV0041GetShares200ResponseSharesSharesInner{}
	return &this
}

// NewSlurmV0041GetShares200ResponseSharesSharesInnerWithDefaults instantiates a new SlurmV0041GetShares200ResponseSharesSharesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmV0041GetShares200ResponseSharesSharesInnerWithDefaults() *SlurmV0041GetShares200ResponseSharesSharesInner {
	this := SlurmV0041GetShares200ResponseSharesSharesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetId(v int32) {
	o.Id = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetCluster() string {
	if o == nil || IsNil(o.Cluster) {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetClusterOk() (*string, bool) {
	if o == nil || IsNil(o.Cluster) {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasCluster() bool {
	if o != nil && !IsNil(o.Cluster) {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetCluster(v string) {
	o.Cluster = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetName(v string) {
	o.Name = &v
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetParent() string {
	if o == nil || IsNil(o.Parent) {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetParentOk() (*string, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetParent(v string) {
	o.Parent = &v
}

// GetPartition returns the Partition field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetPartition() string {
	if o == nil || IsNil(o.Partition) {
		var ret string
		return ret
	}
	return *o.Partition
}

// GetPartitionOk returns a tuple with the Partition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetPartitionOk() (*string, bool) {
	if o == nil || IsNil(o.Partition) {
		return nil, false
	}
	return o.Partition, true
}

// HasPartition returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasPartition() bool {
	if o != nil && !IsNil(o.Partition) {
		return true
	}

	return false
}

// SetPartition gets a reference to the given string and assigns it to the Partition field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetPartition(v string) {
	o.Partition = &v
}

// GetSharesNormalized returns the SharesNormalized field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetSharesNormalized() SlurmV0041GetShares200ResponseSharesSharesInnerSharesNormalized {
	if o == nil || IsNil(o.SharesNormalized) {
		var ret SlurmV0041GetShares200ResponseSharesSharesInnerSharesNormalized
		return ret
	}
	return *o.SharesNormalized
}

// GetSharesNormalizedOk returns a tuple with the SharesNormalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetSharesNormalizedOk() (*SlurmV0041GetShares200ResponseSharesSharesInnerSharesNormalized, bool) {
	if o == nil || IsNil(o.SharesNormalized) {
		return nil, false
	}
	return o.SharesNormalized, true
}

// HasSharesNormalized returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasSharesNormalized() bool {
	if o != nil && !IsNil(o.SharesNormalized) {
		return true
	}

	return false
}

// SetSharesNormalized gets a reference to the given SlurmV0041GetShares200ResponseSharesSharesInnerSharesNormalized and assigns it to the SharesNormalized field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetSharesNormalized(v SlurmV0041GetShares200ResponseSharesSharesInnerSharesNormalized) {
	o.SharesNormalized = &v
}

// GetShares returns the Shares field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetShares() SlurmV0041GetShares200ResponseSharesSharesInnerShares {
	if o == nil || IsNil(o.Shares) {
		var ret SlurmV0041GetShares200ResponseSharesSharesInnerShares
		return ret
	}
	return *o.Shares
}

// GetSharesOk returns a tuple with the Shares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetSharesOk() (*SlurmV0041GetShares200ResponseSharesSharesInnerShares, bool) {
	if o == nil || IsNil(o.Shares) {
		return nil, false
	}
	return o.Shares, true
}

// HasShares returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasShares() bool {
	if o != nil && !IsNil(o.Shares) {
		return true
	}

	return false
}

// SetShares gets a reference to the given SlurmV0041GetShares200ResponseSharesSharesInnerShares and assigns it to the Shares field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetShares(v SlurmV0041GetShares200ResponseSharesSharesInnerShares) {
	o.Shares = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetTres() SlurmV0041GetShares200ResponseSharesSharesInnerTres {
	if o == nil || IsNil(o.Tres) {
		var ret SlurmV0041GetShares200ResponseSharesSharesInnerTres
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetTresOk() (*SlurmV0041GetShares200ResponseSharesSharesInnerTres, bool) {
	if o == nil || IsNil(o.Tres) {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasTres() bool {
	if o != nil && !IsNil(o.Tres) {
		return true
	}

	return false
}

// SetTres gets a reference to the given SlurmV0041GetShares200ResponseSharesSharesInnerTres and assigns it to the Tres field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetTres(v SlurmV0041GetShares200ResponseSharesSharesInnerTres) {
	o.Tres = &v
}

// GetEffectiveUsage returns the EffectiveUsage field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetEffectiveUsage() float64 {
	if o == nil || IsNil(o.EffectiveUsage) {
		var ret float64
		return ret
	}
	return *o.EffectiveUsage
}

// GetEffectiveUsageOk returns a tuple with the EffectiveUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetEffectiveUsageOk() (*float64, bool) {
	if o == nil || IsNil(o.EffectiveUsage) {
		return nil, false
	}
	return o.EffectiveUsage, true
}

// HasEffectiveUsage returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasEffectiveUsage() bool {
	if o != nil && !IsNil(o.EffectiveUsage) {
		return true
	}

	return false
}

// SetEffectiveUsage gets a reference to the given float64 and assigns it to the EffectiveUsage field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetEffectiveUsage(v float64) {
	o.EffectiveUsage = &v
}

// GetUsageNormalized returns the UsageNormalized field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetUsageNormalized() SlurmV0041GetShares200ResponseSharesSharesInnerUsageNormalized {
	if o == nil || IsNil(o.UsageNormalized) {
		var ret SlurmV0041GetShares200ResponseSharesSharesInnerUsageNormalized
		return ret
	}
	return *o.UsageNormalized
}

// GetUsageNormalizedOk returns a tuple with the UsageNormalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetUsageNormalizedOk() (*SlurmV0041GetShares200ResponseSharesSharesInnerUsageNormalized, bool) {
	if o == nil || IsNil(o.UsageNormalized) {
		return nil, false
	}
	return o.UsageNormalized, true
}

// HasUsageNormalized returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasUsageNormalized() bool {
	if o != nil && !IsNil(o.UsageNormalized) {
		return true
	}

	return false
}

// SetUsageNormalized gets a reference to the given SlurmV0041GetShares200ResponseSharesSharesInnerUsageNormalized and assigns it to the UsageNormalized field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetUsageNormalized(v SlurmV0041GetShares200ResponseSharesSharesInnerUsageNormalized) {
	o.UsageNormalized = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetUsage() int64 {
	if o == nil || IsNil(o.Usage) {
		var ret int64
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetUsageOk() (*int64, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given int64 and assigns it to the Usage field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetUsage(v int64) {
	o.Usage = &v
}

// GetFairshare returns the Fairshare field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetFairshare() SlurmV0041GetShares200ResponseSharesSharesInnerFairshare {
	if o == nil || IsNil(o.Fairshare) {
		var ret SlurmV0041GetShares200ResponseSharesSharesInnerFairshare
		return ret
	}
	return *o.Fairshare
}

// GetFairshareOk returns a tuple with the Fairshare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetFairshareOk() (*SlurmV0041GetShares200ResponseSharesSharesInnerFairshare, bool) {
	if o == nil || IsNil(o.Fairshare) {
		return nil, false
	}
	return o.Fairshare, true
}

// HasFairshare returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasFairshare() bool {
	if o != nil && !IsNil(o.Fairshare) {
		return true
	}

	return false
}

// SetFairshare gets a reference to the given SlurmV0041GetShares200ResponseSharesSharesInnerFairshare and assigns it to the Fairshare field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetFairshare(v SlurmV0041GetShares200ResponseSharesSharesInnerFairshare) {
	o.Fairshare = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetType() []string {
	if o == nil || IsNil(o.Type) {
		var ret []string
		return ret
	}
	return o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) GetTypeOk() ([]string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given []string and assigns it to the Type field.
func (o *SlurmV0041GetShares200ResponseSharesSharesInner) SetType(v []string) {
	o.Type = v
}

func (o SlurmV0041GetShares200ResponseSharesSharesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmV0041GetShares200ResponseSharesSharesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Cluster) {
		toSerialize["cluster"] = o.Cluster
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	if !IsNil(o.Partition) {
		toSerialize["partition"] = o.Partition
	}
	if !IsNil(o.SharesNormalized) {
		toSerialize["shares_normalized"] = o.SharesNormalized
	}
	if !IsNil(o.Shares) {
		toSerialize["shares"] = o.Shares
	}
	if !IsNil(o.Tres) {
		toSerialize["tres"] = o.Tres
	}
	if !IsNil(o.EffectiveUsage) {
		toSerialize["effective_usage"] = o.EffectiveUsage
	}
	if !IsNil(o.UsageNormalized) {
		toSerialize["usage_normalized"] = o.UsageNormalized
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !IsNil(o.Fairshare) {
		toSerialize["fairshare"] = o.Fairshare
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableSlurmV0041GetShares200ResponseSharesSharesInner struct {
	value *SlurmV0041GetShares200ResponseSharesSharesInner
	isSet bool
}

func (v NullableSlurmV0041GetShares200ResponseSharesSharesInner) Get() *SlurmV0041GetShares200ResponseSharesSharesInner {
	return v.value
}

func (v *NullableSlurmV0041GetShares200ResponseSharesSharesInner) Set(val *SlurmV0041GetShares200ResponseSharesSharesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmV0041GetShares200ResponseSharesSharesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmV0041GetShares200ResponseSharesSharesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmV0041GetShares200ResponseSharesSharesInner(val *SlurmV0041GetShares200ResponseSharesSharesInner) *NullableSlurmV0041GetShares200ResponseSharesSharesInner {
	return &NullableSlurmV0041GetShares200ResponseSharesSharesInner{value: val, isSet: true}
}

func (v NullableSlurmV0041GetShares200ResponseSharesSharesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmV0041GetShares200ResponseSharesSharesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


