/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0044StepTresConsumed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044StepTresConsumed{}

// V0044StepTresConsumed struct for V0044StepTresConsumed
type V0044StepTresConsumed struct {
	Max []V0044Tres `json:"max,omitempty"`
	Min []V0044Tres `json:"min,omitempty"`
	Average []V0044Tres `json:"average,omitempty"`
	Total []V0044Tres `json:"total,omitempty"`
}

// NewV0044StepTresConsumed instantiates a new V0044StepTresConsumed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044StepTresConsumed() *V0044StepTresConsumed {
	this := V0044StepTresConsumed{}
	return &this
}

// NewV0044StepTresConsumedWithDefaults instantiates a new V0044StepTresConsumed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044StepTresConsumedWithDefaults() *V0044StepTresConsumed {
	this := V0044StepTresConsumed{}
	return &this
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *V0044StepTresConsumed) GetMax() []V0044Tres {
	if o == nil || IsNil(o.Max) {
		var ret []V0044Tres
		return ret
	}
	return o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTresConsumed) GetMaxOk() ([]V0044Tres, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *V0044StepTresConsumed) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given []V0044Tres and assigns it to the Max field.
func (o *V0044StepTresConsumed) SetMax(v []V0044Tres) {
	o.Max = v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *V0044StepTresConsumed) GetMin() []V0044Tres {
	if o == nil || IsNil(o.Min) {
		var ret []V0044Tres
		return ret
	}
	return o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTresConsumed) GetMinOk() ([]V0044Tres, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *V0044StepTresConsumed) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given []V0044Tres and assigns it to the Min field.
func (o *V0044StepTresConsumed) SetMin(v []V0044Tres) {
	o.Min = v
}

// GetAverage returns the Average field value if set, zero value otherwise.
func (o *V0044StepTresConsumed) GetAverage() []V0044Tres {
	if o == nil || IsNil(o.Average) {
		var ret []V0044Tres
		return ret
	}
	return o.Average
}

// GetAverageOk returns a tuple with the Average field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTresConsumed) GetAverageOk() ([]V0044Tres, bool) {
	if o == nil || IsNil(o.Average) {
		return nil, false
	}
	return o.Average, true
}

// HasAverage returns a boolean if a field has been set.
func (o *V0044StepTresConsumed) HasAverage() bool {
	if o != nil && !IsNil(o.Average) {
		return true
	}

	return false
}

// SetAverage gets a reference to the given []V0044Tres and assigns it to the Average field.
func (o *V0044StepTresConsumed) SetAverage(v []V0044Tres) {
	o.Average = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *V0044StepTresConsumed) GetTotal() []V0044Tres {
	if o == nil || IsNil(o.Total) {
		var ret []V0044Tres
		return ret
	}
	return o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTresConsumed) GetTotalOk() ([]V0044Tres, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *V0044StepTresConsumed) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given []V0044Tres and assigns it to the Total field.
func (o *V0044StepTresConsumed) SetTotal(v []V0044Tres) {
	o.Total = v
}

func (o V0044StepTresConsumed) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044StepTresConsumed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Average) {
		toSerialize["average"] = o.Average
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableV0044StepTresConsumed struct {
	value *V0044StepTresConsumed
	isSet bool
}

func (v NullableV0044StepTresConsumed) Get() *V0044StepTresConsumed {
	return v.value
}

func (v *NullableV0044StepTresConsumed) Set(val *V0044StepTresConsumed) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044StepTresConsumed) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044StepTresConsumed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044StepTresConsumed(val *V0044StepTresConsumed) *NullableV0044StepTresConsumed {
	return &NullableV0044StepTresConsumed{value: val, isSet: true}
}

func (v NullableV0044StepTresConsumed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044StepTresConsumed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


