/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0042Qos type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0042Qos{}

// V0042Qos struct for V0042Qos
type V0042Qos struct {
	// Arbitrary description
	Description *string `json:"description,omitempty"`
	Flags []string `json:"flags,omitempty"`
	// Unique ID
	Id *int32 `json:"id,omitempty"`
	Limits *V0042QosLimits `json:"limits,omitempty"`
	// Name
	Name *string `json:"name,omitempty"`
	Preempt *V0042QosPreempt `json:"preempt,omitempty"`
	Priority *V0042Uint32NoValStruct `json:"priority,omitempty"`
	UsageFactor *V0042Float64NoValStruct `json:"usage_factor,omitempty"`
	UsageThreshold *V0042Float64NoValStruct `json:"usage_threshold,omitempty"`
}

// NewV0042Qos instantiates a new V0042Qos object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042Qos() *V0042Qos {
	this := V0042Qos{}
	return &this
}

// NewV0042QosWithDefaults instantiates a new V0042Qos object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042QosWithDefaults() *V0042Qos {
	this := V0042Qos{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *V0042Qos) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *V0042Qos) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *V0042Qos) SetDescription(v string) {
	o.Description = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *V0042Qos) GetFlags() []string {
	if o == nil || IsNil(o.Flags) {
		var ret []string
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetFlagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *V0042Qos) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *V0042Qos) SetFlags(v []string) {
	o.Flags = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V0042Qos) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V0042Qos) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *V0042Qos) SetId(v int32) {
	o.Id = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *V0042Qos) GetLimits() V0042QosLimits {
	if o == nil || IsNil(o.Limits) {
		var ret V0042QosLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetLimitsOk() (*V0042QosLimits, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *V0042Qos) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given V0042QosLimits and assigns it to the Limits field.
func (o *V0042Qos) SetLimits(v V0042QosLimits) {
	o.Limits = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V0042Qos) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V0042Qos) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V0042Qos) SetName(v string) {
	o.Name = &v
}

// GetPreempt returns the Preempt field value if set, zero value otherwise.
func (o *V0042Qos) GetPreempt() V0042QosPreempt {
	if o == nil || IsNil(o.Preempt) {
		var ret V0042QosPreempt
		return ret
	}
	return *o.Preempt
}

// GetPreemptOk returns a tuple with the Preempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetPreemptOk() (*V0042QosPreempt, bool) {
	if o == nil || IsNil(o.Preempt) {
		return nil, false
	}
	return o.Preempt, true
}

// HasPreempt returns a boolean if a field has been set.
func (o *V0042Qos) HasPreempt() bool {
	if o != nil && !IsNil(o.Preempt) {
		return true
	}

	return false
}

// SetPreempt gets a reference to the given V0042QosPreempt and assigns it to the Preempt field.
func (o *V0042Qos) SetPreempt(v V0042QosPreempt) {
	o.Preempt = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *V0042Qos) GetPriority() V0042Uint32NoValStruct {
	if o == nil || IsNil(o.Priority) {
		var ret V0042Uint32NoValStruct
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetPriorityOk() (*V0042Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *V0042Qos) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given V0042Uint32NoValStruct and assigns it to the Priority field.
func (o *V0042Qos) SetPriority(v V0042Uint32NoValStruct) {
	o.Priority = &v
}

// GetUsageFactor returns the UsageFactor field value if set, zero value otherwise.
func (o *V0042Qos) GetUsageFactor() V0042Float64NoValStruct {
	if o == nil || IsNil(o.UsageFactor) {
		var ret V0042Float64NoValStruct
		return ret
	}
	return *o.UsageFactor
}

// GetUsageFactorOk returns a tuple with the UsageFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetUsageFactorOk() (*V0042Float64NoValStruct, bool) {
	if o == nil || IsNil(o.UsageFactor) {
		return nil, false
	}
	return o.UsageFactor, true
}

// HasUsageFactor returns a boolean if a field has been set.
func (o *V0042Qos) HasUsageFactor() bool {
	if o != nil && !IsNil(o.UsageFactor) {
		return true
	}

	return false
}

// SetUsageFactor gets a reference to the given V0042Float64NoValStruct and assigns it to the UsageFactor field.
func (o *V0042Qos) SetUsageFactor(v V0042Float64NoValStruct) {
	o.UsageFactor = &v
}

// GetUsageThreshold returns the UsageThreshold field value if set, zero value otherwise.
func (o *V0042Qos) GetUsageThreshold() V0042Float64NoValStruct {
	if o == nil || IsNil(o.UsageThreshold) {
		var ret V0042Float64NoValStruct
		return ret
	}
	return *o.UsageThreshold
}

// GetUsageThresholdOk returns a tuple with the UsageThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Qos) GetUsageThresholdOk() (*V0042Float64NoValStruct, bool) {
	if o == nil || IsNil(o.UsageThreshold) {
		return nil, false
	}
	return o.UsageThreshold, true
}

// HasUsageThreshold returns a boolean if a field has been set.
func (o *V0042Qos) HasUsageThreshold() bool {
	if o != nil && !IsNil(o.UsageThreshold) {
		return true
	}

	return false
}

// SetUsageThreshold gets a reference to the given V0042Float64NoValStruct and assigns it to the UsageThreshold field.
func (o *V0042Qos) SetUsageThreshold(v V0042Float64NoValStruct) {
	o.UsageThreshold = &v
}

func (o V0042Qos) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0042Qos) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Preempt) {
		toSerialize["preempt"] = o.Preempt
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.UsageFactor) {
		toSerialize["usage_factor"] = o.UsageFactor
	}
	if !IsNil(o.UsageThreshold) {
		toSerialize["usage_threshold"] = o.UsageThreshold
	}
	return toSerialize, nil
}

type NullableV0042Qos struct {
	value *V0042Qos
	isSet bool
}

func (v NullableV0042Qos) Get() *V0042Qos {
	return v.value
}

func (v *NullableV0042Qos) Set(val *V0042Qos) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042Qos) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042Qos) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042Qos(val *V0042Qos) *NullableV0042Qos {
	return &NullableV0042Qos{value: val, isSet: true}
}

func (v NullableV0042Qos) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042Qos) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


