/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0044JobArrayResponseMsgEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044JobArrayResponseMsgEntry{}

// V0044JobArrayResponseMsgEntry struct for V0044JobArrayResponseMsgEntry
type V0044JobArrayResponseMsgEntry struct {
	// Job ID for updated job
	JobId *int32 `json:"job_id,omitempty"`
	// Step ID for updated job
	StepId *string `json:"step_id,omitempty"`
	// Verbose update status or error
	Error *string `json:"error,omitempty"`
	// Verbose update status or error
	ErrorCode *int32 `json:"error_code,omitempty"`
	// Update response message
	Why *string `json:"why,omitempty"`
}

// NewV0044JobArrayResponseMsgEntry instantiates a new V0044JobArrayResponseMsgEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044JobArrayResponseMsgEntry() *V0044JobArrayResponseMsgEntry {
	this := V0044JobArrayResponseMsgEntry{}
	return &this
}

// NewV0044JobArrayResponseMsgEntryWithDefaults instantiates a new V0044JobArrayResponseMsgEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044JobArrayResponseMsgEntryWithDefaults() *V0044JobArrayResponseMsgEntry {
	this := V0044JobArrayResponseMsgEntry{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *V0044JobArrayResponseMsgEntry) GetJobId() int32 {
	if o == nil || IsNil(o.JobId) {
		var ret int32
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobArrayResponseMsgEntry) GetJobIdOk() (*int32, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *V0044JobArrayResponseMsgEntry) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given int32 and assigns it to the JobId field.
func (o *V0044JobArrayResponseMsgEntry) SetJobId(v int32) {
	o.JobId = &v
}

// GetStepId returns the StepId field value if set, zero value otherwise.
func (o *V0044JobArrayResponseMsgEntry) GetStepId() string {
	if o == nil || IsNil(o.StepId) {
		var ret string
		return ret
	}
	return *o.StepId
}

// GetStepIdOk returns a tuple with the StepId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobArrayResponseMsgEntry) GetStepIdOk() (*string, bool) {
	if o == nil || IsNil(o.StepId) {
		return nil, false
	}
	return o.StepId, true
}

// HasStepId returns a boolean if a field has been set.
func (o *V0044JobArrayResponseMsgEntry) HasStepId() bool {
	if o != nil && !IsNil(o.StepId) {
		return true
	}

	return false
}

// SetStepId gets a reference to the given string and assigns it to the StepId field.
func (o *V0044JobArrayResponseMsgEntry) SetStepId(v string) {
	o.StepId = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *V0044JobArrayResponseMsgEntry) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobArrayResponseMsgEntry) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *V0044JobArrayResponseMsgEntry) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *V0044JobArrayResponseMsgEntry) SetError(v string) {
	o.Error = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *V0044JobArrayResponseMsgEntry) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode) {
		var ret int32
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobArrayResponseMsgEntry) GetErrorCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *V0044JobArrayResponseMsgEntry) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given int32 and assigns it to the ErrorCode field.
func (o *V0044JobArrayResponseMsgEntry) SetErrorCode(v int32) {
	o.ErrorCode = &v
}

// GetWhy returns the Why field value if set, zero value otherwise.
func (o *V0044JobArrayResponseMsgEntry) GetWhy() string {
	if o == nil || IsNil(o.Why) {
		var ret string
		return ret
	}
	return *o.Why
}

// GetWhyOk returns a tuple with the Why field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobArrayResponseMsgEntry) GetWhyOk() (*string, bool) {
	if o == nil || IsNil(o.Why) {
		return nil, false
	}
	return o.Why, true
}

// HasWhy returns a boolean if a field has been set.
func (o *V0044JobArrayResponseMsgEntry) HasWhy() bool {
	if o != nil && !IsNil(o.Why) {
		return true
	}

	return false
}

// SetWhy gets a reference to the given string and assigns it to the Why field.
func (o *V0044JobArrayResponseMsgEntry) SetWhy(v string) {
	o.Why = &v
}

func (o V0044JobArrayResponseMsgEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044JobArrayResponseMsgEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.StepId) {
		toSerialize["step_id"] = o.StepId
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["error_code"] = o.ErrorCode
	}
	if !IsNil(o.Why) {
		toSerialize["why"] = o.Why
	}
	return toSerialize, nil
}

type NullableV0044JobArrayResponseMsgEntry struct {
	value *V0044JobArrayResponseMsgEntry
	isSet bool
}

func (v NullableV0044JobArrayResponseMsgEntry) Get() *V0044JobArrayResponseMsgEntry {
	return v.value
}

func (v *NullableV0044JobArrayResponseMsgEntry) Set(val *V0044JobArrayResponseMsgEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044JobArrayResponseMsgEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044JobArrayResponseMsgEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044JobArrayResponseMsgEntry(val *V0044JobArrayResponseMsgEntry) *NullableV0044JobArrayResponseMsgEntry {
	return &NullableV0044JobArrayResponseMsgEntry{value: val, isSet: true}
}

func (v NullableV0044JobArrayResponseMsgEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044JobArrayResponseMsgEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


