/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0044UserDefault type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044UserDefault{}

// V0044UserDefault struct for V0044UserDefault
type V0044UserDefault struct {
	// Default QOS
	Qos *int32 `json:"qos,omitempty"`
	// Default account
	Account *string `json:"account,omitempty"`
	// Default WCKey
	Wckey *string `json:"wckey,omitempty"`
}

// NewV0044UserDefault instantiates a new V0044UserDefault object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044UserDefault() *V0044UserDefault {
	this := V0044UserDefault{}
	return &this
}

// NewV0044UserDefaultWithDefaults instantiates a new V0044UserDefault object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044UserDefaultWithDefaults() *V0044UserDefault {
	this := V0044UserDefault{}
	return &this
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *V0044UserDefault) GetQos() int32 {
	if o == nil || IsNil(o.Qos) {
		var ret int32
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044UserDefault) GetQosOk() (*int32, bool) {
	if o == nil || IsNil(o.Qos) {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *V0044UserDefault) HasQos() bool {
	if o != nil && !IsNil(o.Qos) {
		return true
	}

	return false
}

// SetQos gets a reference to the given int32 and assigns it to the Qos field.
func (o *V0044UserDefault) SetQos(v int32) {
	o.Qos = &v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *V0044UserDefault) GetAccount() string {
	if o == nil || IsNil(o.Account) {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044UserDefault) GetAccountOk() (*string, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *V0044UserDefault) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *V0044UserDefault) SetAccount(v string) {
	o.Account = &v
}

// GetWckey returns the Wckey field value if set, zero value otherwise.
func (o *V0044UserDefault) GetWckey() string {
	if o == nil || IsNil(o.Wckey) {
		var ret string
		return ret
	}
	return *o.Wckey
}

// GetWckeyOk returns a tuple with the Wckey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044UserDefault) GetWckeyOk() (*string, bool) {
	if o == nil || IsNil(o.Wckey) {
		return nil, false
	}
	return o.Wckey, true
}

// HasWckey returns a boolean if a field has been set.
func (o *V0044UserDefault) HasWckey() bool {
	if o != nil && !IsNil(o.Wckey) {
		return true
	}

	return false
}

// SetWckey gets a reference to the given string and assigns it to the Wckey field.
func (o *V0044UserDefault) SetWckey(v string) {
	o.Wckey = &v
}

func (o V0044UserDefault) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044UserDefault) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Qos) {
		toSerialize["qos"] = o.Qos
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Wckey) {
		toSerialize["wckey"] = o.Wckey
	}
	return toSerialize, nil
}

type NullableV0044UserDefault struct {
	value *V0044UserDefault
	isSet bool
}

func (v NullableV0044UserDefault) Get() *V0044UserDefault {
	return v.value
}

func (v *NullableV0044UserDefault) Set(val *V0044UserDefault) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044UserDefault) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044UserDefault) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044UserDefault(val *V0044UserDefault) *NullableV0044UserDefault {
	return &NullableV0044UserDefault{value: val, isSet: true}
}

func (v NullableV0044UserDefault) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044UserDefault) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


