/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData{}

// SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData Maximum size of data segment, in bytes. 
type SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int64 `json:"number,omitempty"`
}

// NewSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData instantiates a new SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData() *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData {
	this := SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData{}
	return &this
}

// NewSlurmV0041PostJobSubmitRequestJobsInnerRlimitsDataWithDefaults instantiates a new SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmV0041PostJobSubmitRequestJobsInnerRlimitsDataWithDefaults() *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData {
	this := SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) GetSet() bool {
	if o == nil || IsNil(o.Set) {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) GetSetOk() (*bool, bool) {
	if o == nil || IsNil(o.Set) {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) HasSet() bool {
	if o != nil && !IsNil(o.Set) {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) GetInfinite() bool {
	if o == nil || IsNil(o.Infinite) {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) GetInfiniteOk() (*bool, bool) {
	if o == nil || IsNil(o.Infinite) {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) HasInfinite() bool {
	if o != nil && !IsNil(o.Infinite) {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) GetNumber() int64 {
	if o == nil || IsNil(o.Number) {
		var ret int64
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) GetNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int64 and assigns it to the Number field.
func (o *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) SetNumber(v int64) {
	o.Number = &v
}

func (o SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Set) {
		toSerialize["set"] = o.Set
	}
	if !IsNil(o.Infinite) {
		toSerialize["infinite"] = o.Infinite
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	return toSerialize, nil
}

type NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData struct {
	value *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData
	isSet bool
}

func (v NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) Get() *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData {
	return v.value
}

func (v *NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) Set(val *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData(val *SlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) *NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData {
	return &NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData{value: val, isSet: true}
}

func (v NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmV0041PostJobSubmitRequestJobsInnerRlimitsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


