/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0044QosLimitsMaxTres type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044QosLimitsMaxTres{}

// V0044QosLimitsMaxTres struct for V0044QosLimitsMaxTres
type V0044QosLimitsMaxTres struct {
	Total []V0044Tres `json:"total,omitempty"`
	Minutes *V0044QosLimitsMaxTresMinutes `json:"minutes,omitempty"`
	Per *V0044QosLimitsMaxTresPer `json:"per,omitempty"`
}

// NewV0044QosLimitsMaxTres instantiates a new V0044QosLimitsMaxTres object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044QosLimitsMaxTres() *V0044QosLimitsMaxTres {
	this := V0044QosLimitsMaxTres{}
	return &this
}

// NewV0044QosLimitsMaxTresWithDefaults instantiates a new V0044QosLimitsMaxTres object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044QosLimitsMaxTresWithDefaults() *V0044QosLimitsMaxTres {
	this := V0044QosLimitsMaxTres{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *V0044QosLimitsMaxTres) GetTotal() []V0044Tres {
	if o == nil || IsNil(o.Total) {
		var ret []V0044Tres
		return ret
	}
	return o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044QosLimitsMaxTres) GetTotalOk() ([]V0044Tres, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *V0044QosLimitsMaxTres) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given []V0044Tres and assigns it to the Total field.
func (o *V0044QosLimitsMaxTres) SetTotal(v []V0044Tres) {
	o.Total = v
}

// GetMinutes returns the Minutes field value if set, zero value otherwise.
func (o *V0044QosLimitsMaxTres) GetMinutes() V0044QosLimitsMaxTresMinutes {
	if o == nil || IsNil(o.Minutes) {
		var ret V0044QosLimitsMaxTresMinutes
		return ret
	}
	return *o.Minutes
}

// GetMinutesOk returns a tuple with the Minutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044QosLimitsMaxTres) GetMinutesOk() (*V0044QosLimitsMaxTresMinutes, bool) {
	if o == nil || IsNil(o.Minutes) {
		return nil, false
	}
	return o.Minutes, true
}

// HasMinutes returns a boolean if a field has been set.
func (o *V0044QosLimitsMaxTres) HasMinutes() bool {
	if o != nil && !IsNil(o.Minutes) {
		return true
	}

	return false
}

// SetMinutes gets a reference to the given V0044QosLimitsMaxTresMinutes and assigns it to the Minutes field.
func (o *V0044QosLimitsMaxTres) SetMinutes(v V0044QosLimitsMaxTresMinutes) {
	o.Minutes = &v
}

// GetPer returns the Per field value if set, zero value otherwise.
func (o *V0044QosLimitsMaxTres) GetPer() V0044QosLimitsMaxTresPer {
	if o == nil || IsNil(o.Per) {
		var ret V0044QosLimitsMaxTresPer
		return ret
	}
	return *o.Per
}

// GetPerOk returns a tuple with the Per field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044QosLimitsMaxTres) GetPerOk() (*V0044QosLimitsMaxTresPer, bool) {
	if o == nil || IsNil(o.Per) {
		return nil, false
	}
	return o.Per, true
}

// HasPer returns a boolean if a field has been set.
func (o *V0044QosLimitsMaxTres) HasPer() bool {
	if o != nil && !IsNil(o.Per) {
		return true
	}

	return false
}

// SetPer gets a reference to the given V0044QosLimitsMaxTresPer and assigns it to the Per field.
func (o *V0044QosLimitsMaxTres) SetPer(v V0044QosLimitsMaxTresPer) {
	o.Per = &v
}

func (o V0044QosLimitsMaxTres) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044QosLimitsMaxTres) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Minutes) {
		toSerialize["minutes"] = o.Minutes
	}
	if !IsNil(o.Per) {
		toSerialize["per"] = o.Per
	}
	return toSerialize, nil
}

type NullableV0044QosLimitsMaxTres struct {
	value *V0044QosLimitsMaxTres
	isSet bool
}

func (v NullableV0044QosLimitsMaxTres) Get() *V0044QosLimitsMaxTres {
	return v.value
}

func (v *NullableV0044QosLimitsMaxTres) Set(val *V0044QosLimitsMaxTres) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044QosLimitsMaxTres) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044QosLimitsMaxTres) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044QosLimitsMaxTres(val *V0044QosLimitsMaxTres) *NullableV0044QosLimitsMaxTres {
	return &NullableV0044QosLimitsMaxTres{value: val, isSet: true}
}

func (v NullableV0044QosLimitsMaxTres) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044QosLimitsMaxTres) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


