/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue{}

// SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue Maximum number of pending jobs able to accrue age priority at any given time in this association
type SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int32 `json:"number,omitempty"`
}

// NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue instantiates a new SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue() *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue {
	this := SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue{}
	return &this
}

// NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrueWithDefaults instantiates a new SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrueWithDefaults() *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue {
	this := SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) GetSet() bool {
	if o == nil || IsNil(o.Set) {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) GetSetOk() (*bool, bool) {
	if o == nil || IsNil(o.Set) {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) HasSet() bool {
	if o != nil && !IsNil(o.Set) {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) GetInfinite() bool {
	if o == nil || IsNil(o.Infinite) {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) GetInfiniteOk() (*bool, bool) {
	if o == nil || IsNil(o.Infinite) {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) HasInfinite() bool {
	if o != nil && !IsNil(o.Infinite) {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) SetNumber(v int32) {
	o.Number = &v
}

func (o SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Set) {
		toSerialize["set"] = o.Set
	}
	if !IsNil(o.Infinite) {
		toSerialize["infinite"] = o.Infinite
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	return toSerialize, nil
}

type NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue struct {
	value *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue
	isSet bool
}

func (v NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) Get() *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue {
	return v.value
}

func (v *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) Set(val *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue(val *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue {
	return &NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue{value: val, isSet: true}
}

func (v NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationMaxjobsaccrue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


