/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0044QosLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044QosLimits{}

// V0044QosLimits struct for V0044QosLimits
type V0044QosLimits struct {
	// GraceTime - Preemption grace time in seconds to be extended to a job which has been selected for preemption
	GraceTime *int32 `json:"grace_time,omitempty"`
	Max *V0044QosLimitsMax `json:"max,omitempty"`
	Factor *V0044Float64NoValStruct `json:"factor,omitempty"`
	Min *V0044QosLimitsMin `json:"min,omitempty"`
}

// NewV0044QosLimits instantiates a new V0044QosLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044QosLimits() *V0044QosLimits {
	this := V0044QosLimits{}
	return &this
}

// NewV0044QosLimitsWithDefaults instantiates a new V0044QosLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044QosLimitsWithDefaults() *V0044QosLimits {
	this := V0044QosLimits{}
	return &this
}

// GetGraceTime returns the GraceTime field value if set, zero value otherwise.
func (o *V0044QosLimits) GetGraceTime() int32 {
	if o == nil || IsNil(o.GraceTime) {
		var ret int32
		return ret
	}
	return *o.GraceTime
}

// GetGraceTimeOk returns a tuple with the GraceTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044QosLimits) GetGraceTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.GraceTime) {
		return nil, false
	}
	return o.GraceTime, true
}

// HasGraceTime returns a boolean if a field has been set.
func (o *V0044QosLimits) HasGraceTime() bool {
	if o != nil && !IsNil(o.GraceTime) {
		return true
	}

	return false
}

// SetGraceTime gets a reference to the given int32 and assigns it to the GraceTime field.
func (o *V0044QosLimits) SetGraceTime(v int32) {
	o.GraceTime = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *V0044QosLimits) GetMax() V0044QosLimitsMax {
	if o == nil || IsNil(o.Max) {
		var ret V0044QosLimitsMax
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044QosLimits) GetMaxOk() (*V0044QosLimitsMax, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *V0044QosLimits) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given V0044QosLimitsMax and assigns it to the Max field.
func (o *V0044QosLimits) SetMax(v V0044QosLimitsMax) {
	o.Max = &v
}

// GetFactor returns the Factor field value if set, zero value otherwise.
func (o *V0044QosLimits) GetFactor() V0044Float64NoValStruct {
	if o == nil || IsNil(o.Factor) {
		var ret V0044Float64NoValStruct
		return ret
	}
	return *o.Factor
}

// GetFactorOk returns a tuple with the Factor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044QosLimits) GetFactorOk() (*V0044Float64NoValStruct, bool) {
	if o == nil || IsNil(o.Factor) {
		return nil, false
	}
	return o.Factor, true
}

// HasFactor returns a boolean if a field has been set.
func (o *V0044QosLimits) HasFactor() bool {
	if o != nil && !IsNil(o.Factor) {
		return true
	}

	return false
}

// SetFactor gets a reference to the given V0044Float64NoValStruct and assigns it to the Factor field.
func (o *V0044QosLimits) SetFactor(v V0044Float64NoValStruct) {
	o.Factor = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *V0044QosLimits) GetMin() V0044QosLimitsMin {
	if o == nil || IsNil(o.Min) {
		var ret V0044QosLimitsMin
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044QosLimits) GetMinOk() (*V0044QosLimitsMin, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *V0044QosLimits) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given V0044QosLimitsMin and assigns it to the Min field.
func (o *V0044QosLimits) SetMin(v V0044QosLimitsMin) {
	o.Min = &v
}

func (o V0044QosLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044QosLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GraceTime) {
		toSerialize["grace_time"] = o.GraceTime
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Factor) {
		toSerialize["factor"] = o.Factor
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	return toSerialize, nil
}

type NullableV0044QosLimits struct {
	value *V0044QosLimits
	isSet bool
}

func (v NullableV0044QosLimits) Get() *V0044QosLimits {
	return v.value
}

func (v *NullableV0044QosLimits) Set(val *V0044QosLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044QosLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044QosLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044QosLimits(val *V0044QosLimits) *NullableV0044QosLimits {
	return &NullableV0044QosLimits{value: val, isSet: true}
}

func (v NullableV0044QosLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044QosLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


