/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0044JobSubmitReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044JobSubmitReq{}

// V0044JobSubmitReq struct for V0044JobSubmitReq
type V0044JobSubmitReq struct {
	// Job batch script contents; Same as the script field in jobs[0] or job.
	Script *string `json:"script,omitempty"`
	Jobs []V0044JobDescMsg `json:"jobs,omitempty"`
	Job *V0044JobDescMsg `json:"job,omitempty"`
}

// NewV0044JobSubmitReq instantiates a new V0044JobSubmitReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044JobSubmitReq() *V0044JobSubmitReq {
	this := V0044JobSubmitReq{}
	return &this
}

// NewV0044JobSubmitReqWithDefaults instantiates a new V0044JobSubmitReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044JobSubmitReqWithDefaults() *V0044JobSubmitReq {
	this := V0044JobSubmitReq{}
	return &this
}

// GetScript returns the Script field value if set, zero value otherwise.
func (o *V0044JobSubmitReq) GetScript() string {
	if o == nil || IsNil(o.Script) {
		var ret string
		return ret
	}
	return *o.Script
}

// GetScriptOk returns a tuple with the Script field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobSubmitReq) GetScriptOk() (*string, bool) {
	if o == nil || IsNil(o.Script) {
		return nil, false
	}
	return o.Script, true
}

// HasScript returns a boolean if a field has been set.
func (o *V0044JobSubmitReq) HasScript() bool {
	if o != nil && !IsNil(o.Script) {
		return true
	}

	return false
}

// SetScript gets a reference to the given string and assigns it to the Script field.
func (o *V0044JobSubmitReq) SetScript(v string) {
	o.Script = &v
}

// GetJobs returns the Jobs field value if set, zero value otherwise.
func (o *V0044JobSubmitReq) GetJobs() []V0044JobDescMsg {
	if o == nil || IsNil(o.Jobs) {
		var ret []V0044JobDescMsg
		return ret
	}
	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobSubmitReq) GetJobsOk() ([]V0044JobDescMsg, bool) {
	if o == nil || IsNil(o.Jobs) {
		return nil, false
	}
	return o.Jobs, true
}

// HasJobs returns a boolean if a field has been set.
func (o *V0044JobSubmitReq) HasJobs() bool {
	if o != nil && !IsNil(o.Jobs) {
		return true
	}

	return false
}

// SetJobs gets a reference to the given []V0044JobDescMsg and assigns it to the Jobs field.
func (o *V0044JobSubmitReq) SetJobs(v []V0044JobDescMsg) {
	o.Jobs = v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *V0044JobSubmitReq) GetJob() V0044JobDescMsg {
	if o == nil || IsNil(o.Job) {
		var ret V0044JobDescMsg
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobSubmitReq) GetJobOk() (*V0044JobDescMsg, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *V0044JobSubmitReq) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given V0044JobDescMsg and assigns it to the Job field.
func (o *V0044JobSubmitReq) SetJob(v V0044JobDescMsg) {
	o.Job = &v
}

func (o V0044JobSubmitReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044JobSubmitReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Script) {
		toSerialize["script"] = o.Script
	}
	if !IsNil(o.Jobs) {
		toSerialize["jobs"] = o.Jobs
	}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableV0044JobSubmitReq struct {
	value *V0044JobSubmitReq
	isSet bool
}

func (v NullableV0044JobSubmitReq) Get() *V0044JobSubmitReq {
	return v.value
}

func (v *NullableV0044JobSubmitReq) Set(val *V0044JobSubmitReq) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044JobSubmitReq) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044JobSubmitReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044JobSubmitReq(val *V0044JobSubmitReq) *NullableV0044JobSubmitReq {
	return &NullableV0044JobSubmitReq{value: val, isSet: true}
}

func (v NullableV0044JobSubmitReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044JobSubmitReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


