/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall{}

// SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall Maximum wall clock time in minutes able to be allocated by running jobs in this association and its children
type SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int32 `json:"number,omitempty"`
}

// NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall instantiates a new SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall() *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall {
	this := SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall{}
	return &this
}

// NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwallWithDefaults instantiates a new SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwallWithDefaults() *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall {
	this := SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) GetSet() bool {
	if o == nil || IsNil(o.Set) {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) GetSetOk() (*bool, bool) {
	if o == nil || IsNil(o.Set) {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) HasSet() bool {
	if o != nil && !IsNil(o.Set) {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) GetInfinite() bool {
	if o == nil || IsNil(o.Infinite) {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) GetInfiniteOk() (*bool, bool) {
	if o == nil || IsNil(o.Infinite) {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) HasInfinite() bool {
	if o != nil && !IsNil(o.Infinite) {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) SetNumber(v int32) {
	o.Number = &v
}

func (o SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Set) {
		toSerialize["set"] = o.Set
	}
	if !IsNil(o.Infinite) {
		toSerialize["infinite"] = o.Infinite
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	return toSerialize, nil
}

type NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall struct {
	value *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall
	isSet bool
}

func (v NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) Get() *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall {
	return v.value
}

func (v *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) Set(val *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall(val *SlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall {
	return &NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall{value: val, isSet: true}
}

func (v NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmdbV0041PostUsersAssociationRequestAssociationConditionAssociationGrpwall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


