/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V0044OpenapiAccountsRemovedResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044OpenapiAccountsRemovedResp{}

// V0044OpenapiAccountsRemovedResp struct for V0044OpenapiAccountsRemovedResp
type V0044OpenapiAccountsRemovedResp struct {
	RemovedAccounts []string `json:"removed_accounts"`
	Meta *V0044OpenapiMeta `json:"meta,omitempty"`
	Errors []V0044OpenapiError `json:"errors,omitempty"`
	Warnings []V0044OpenapiWarning `json:"warnings,omitempty"`
}

type _V0044OpenapiAccountsRemovedResp V0044OpenapiAccountsRemovedResp

// NewV0044OpenapiAccountsRemovedResp instantiates a new V0044OpenapiAccountsRemovedResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044OpenapiAccountsRemovedResp(removedAccounts []string) *V0044OpenapiAccountsRemovedResp {
	this := V0044OpenapiAccountsRemovedResp{}
	this.RemovedAccounts = removedAccounts
	return &this
}

// NewV0044OpenapiAccountsRemovedRespWithDefaults instantiates a new V0044OpenapiAccountsRemovedResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044OpenapiAccountsRemovedRespWithDefaults() *V0044OpenapiAccountsRemovedResp {
	this := V0044OpenapiAccountsRemovedResp{}
	return &this
}

// GetRemovedAccounts returns the RemovedAccounts field value
func (o *V0044OpenapiAccountsRemovedResp) GetRemovedAccounts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemovedAccounts
}

// GetRemovedAccountsOk returns a tuple with the RemovedAccounts field value
// and a boolean to check if the value has been set.
func (o *V0044OpenapiAccountsRemovedResp) GetRemovedAccountsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemovedAccounts, true
}

// SetRemovedAccounts sets field value
func (o *V0044OpenapiAccountsRemovedResp) SetRemovedAccounts(v []string) {
	o.RemovedAccounts = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0044OpenapiAccountsRemovedResp) GetMeta() V0044OpenapiMeta {
	if o == nil || IsNil(o.Meta) {
		var ret V0044OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiAccountsRemovedResp) GetMetaOk() (*V0044OpenapiMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0044OpenapiAccountsRemovedResp) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0044OpenapiMeta and assigns it to the Meta field.
func (o *V0044OpenapiAccountsRemovedResp) SetMeta(v V0044OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0044OpenapiAccountsRemovedResp) GetErrors() []V0044OpenapiError {
	if o == nil || IsNil(o.Errors) {
		var ret []V0044OpenapiError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiAccountsRemovedResp) GetErrorsOk() ([]V0044OpenapiError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0044OpenapiAccountsRemovedResp) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0044OpenapiError and assigns it to the Errors field.
func (o *V0044OpenapiAccountsRemovedResp) SetErrors(v []V0044OpenapiError) {
	o.Errors = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0044OpenapiAccountsRemovedResp) GetWarnings() []V0044OpenapiWarning {
	if o == nil || IsNil(o.Warnings) {
		var ret []V0044OpenapiWarning
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiAccountsRemovedResp) GetWarningsOk() ([]V0044OpenapiWarning, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0044OpenapiAccountsRemovedResp) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0044OpenapiWarning and assigns it to the Warnings field.
func (o *V0044OpenapiAccountsRemovedResp) SetWarnings(v []V0044OpenapiWarning) {
	o.Warnings = v
}

func (o V0044OpenapiAccountsRemovedResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044OpenapiAccountsRemovedResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["removed_accounts"] = o.RemovedAccounts
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *V0044OpenapiAccountsRemovedResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"removed_accounts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV0044OpenapiAccountsRemovedResp := _V0044OpenapiAccountsRemovedResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV0044OpenapiAccountsRemovedResp)

	if err != nil {
		return err
	}

	*o = V0044OpenapiAccountsRemovedResp(varV0044OpenapiAccountsRemovedResp)

	return err
}

type NullableV0044OpenapiAccountsRemovedResp struct {
	value *V0044OpenapiAccountsRemovedResp
	isSet bool
}

func (v NullableV0044OpenapiAccountsRemovedResp) Get() *V0044OpenapiAccountsRemovedResp {
	return v.value
}

func (v *NullableV0044OpenapiAccountsRemovedResp) Set(val *V0044OpenapiAccountsRemovedResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044OpenapiAccountsRemovedResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044OpenapiAccountsRemovedResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044OpenapiAccountsRemovedResp(val *V0044OpenapiAccountsRemovedResp) *NullableV0044OpenapiAccountsRemovedResp {
	return &NullableV0044OpenapiAccountsRemovedResp{value: val, isSet: true}
}

func (v NullableV0044OpenapiAccountsRemovedResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044OpenapiAccountsRemovedResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


