/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0043StepCPU type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0043StepCPU{}

// V0043StepCPU struct for V0043StepCPU
type V0043StepCPU struct {
	RequestedFrequency *V0043StepCPURequestedFrequency `json:"requested_frequency,omitempty"`
	// Requested CPU frequency governor in kHz
	Governor *string `json:"governor,omitempty"`
}

// NewV0043StepCPU instantiates a new V0043StepCPU object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043StepCPU() *V0043StepCPU {
	this := V0043StepCPU{}
	return &this
}

// NewV0043StepCPUWithDefaults instantiates a new V0043StepCPU object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043StepCPUWithDefaults() *V0043StepCPU {
	this := V0043StepCPU{}
	return &this
}

// GetRequestedFrequency returns the RequestedFrequency field value if set, zero value otherwise.
func (o *V0043StepCPU) GetRequestedFrequency() V0043StepCPURequestedFrequency {
	if o == nil || IsNil(o.RequestedFrequency) {
		var ret V0043StepCPURequestedFrequency
		return ret
	}
	return *o.RequestedFrequency
}

// GetRequestedFrequencyOk returns a tuple with the RequestedFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043StepCPU) GetRequestedFrequencyOk() (*V0043StepCPURequestedFrequency, bool) {
	if o == nil || IsNil(o.RequestedFrequency) {
		return nil, false
	}
	return o.RequestedFrequency, true
}

// HasRequestedFrequency returns a boolean if a field has been set.
func (o *V0043StepCPU) HasRequestedFrequency() bool {
	if o != nil && !IsNil(o.RequestedFrequency) {
		return true
	}

	return false
}

// SetRequestedFrequency gets a reference to the given V0043StepCPURequestedFrequency and assigns it to the RequestedFrequency field.
func (o *V0043StepCPU) SetRequestedFrequency(v V0043StepCPURequestedFrequency) {
	o.RequestedFrequency = &v
}

// GetGovernor returns the Governor field value if set, zero value otherwise.
func (o *V0043StepCPU) GetGovernor() string {
	if o == nil || IsNil(o.Governor) {
		var ret string
		return ret
	}
	return *o.Governor
}

// GetGovernorOk returns a tuple with the Governor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043StepCPU) GetGovernorOk() (*string, bool) {
	if o == nil || IsNil(o.Governor) {
		return nil, false
	}
	return o.Governor, true
}

// HasGovernor returns a boolean if a field has been set.
func (o *V0043StepCPU) HasGovernor() bool {
	if o != nil && !IsNil(o.Governor) {
		return true
	}

	return false
}

// SetGovernor gets a reference to the given string and assigns it to the Governor field.
func (o *V0043StepCPU) SetGovernor(v string) {
	o.Governor = &v
}

func (o V0043StepCPU) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0043StepCPU) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestedFrequency) {
		toSerialize["requested_frequency"] = o.RequestedFrequency
	}
	if !IsNil(o.Governor) {
		toSerialize["governor"] = o.Governor
	}
	return toSerialize, nil
}

type NullableV0043StepCPU struct {
	value *V0043StepCPU
	isSet bool
}

func (v NullableV0043StepCPU) Get() *V0043StepCPU {
	return v.value
}

func (v *NullableV0043StepCPU) Set(val *V0043StepCPU) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043StepCPU) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043StepCPU) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043StepCPU(val *V0043StepCPU) *NullableV0043StepCPU {
	return &NullableV0043StepCPU{value: val, isSet: true}
}

func (v NullableV0043StepCPU) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043StepCPU) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


