/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0042QosLimitsMaxJobsActiveJobsPer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0042QosLimitsMaxJobsActiveJobsPer{}

// V0042QosLimitsMaxJobsActiveJobsPer struct for V0042QosLimitsMaxJobsActiveJobsPer
type V0042QosLimitsMaxJobsActiveJobsPer struct {
	Account *V0042Uint32NoValStruct `json:"account,omitempty"`
	User *V0042Uint32NoValStruct `json:"user,omitempty"`
}

// NewV0042QosLimitsMaxJobsActiveJobsPer instantiates a new V0042QosLimitsMaxJobsActiveJobsPer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042QosLimitsMaxJobsActiveJobsPer() *V0042QosLimitsMaxJobsActiveJobsPer {
	this := V0042QosLimitsMaxJobsActiveJobsPer{}
	return &this
}

// NewV0042QosLimitsMaxJobsActiveJobsPerWithDefaults instantiates a new V0042QosLimitsMaxJobsActiveJobsPer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042QosLimitsMaxJobsActiveJobsPerWithDefaults() *V0042QosLimitsMaxJobsActiveJobsPer {
	this := V0042QosLimitsMaxJobsActiveJobsPer{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) GetAccount() V0042Uint32NoValStruct {
	if o == nil || IsNil(o.Account) {
		var ret V0042Uint32NoValStruct
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) GetAccountOk() (*V0042Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given V0042Uint32NoValStruct and assigns it to the Account field.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) SetAccount(v V0042Uint32NoValStruct) {
	o.Account = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) GetUser() V0042Uint32NoValStruct {
	if o == nil || IsNil(o.User) {
		var ret V0042Uint32NoValStruct
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) GetUserOk() (*V0042Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given V0042Uint32NoValStruct and assigns it to the User field.
func (o *V0042QosLimitsMaxJobsActiveJobsPer) SetUser(v V0042Uint32NoValStruct) {
	o.User = &v
}

func (o V0042QosLimitsMaxJobsActiveJobsPer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0042QosLimitsMaxJobsActiveJobsPer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableV0042QosLimitsMaxJobsActiveJobsPer struct {
	value *V0042QosLimitsMaxJobsActiveJobsPer
	isSet bool
}

func (v NullableV0042QosLimitsMaxJobsActiveJobsPer) Get() *V0042QosLimitsMaxJobsActiveJobsPer {
	return v.value
}

func (v *NullableV0042QosLimitsMaxJobsActiveJobsPer) Set(val *V0042QosLimitsMaxJobsActiveJobsPer) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042QosLimitsMaxJobsActiveJobsPer) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042QosLimitsMaxJobsActiveJobsPer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042QosLimitsMaxJobsActiveJobsPer(val *V0042QosLimitsMaxJobsActiveJobsPer) *NullableV0042QosLimitsMaxJobsActiveJobsPer {
	return &NullableV0042QosLimitsMaxJobsActiveJobsPer{value: val, isSet: true}
}

func (v NullableV0042QosLimitsMaxJobsActiveJobsPer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042QosLimitsMaxJobsActiveJobsPer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


