/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0044PartitionInfoDefaults type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044PartitionInfoDefaults{}

// V0044PartitionInfoDefaults struct for V0044PartitionInfoDefaults
type V0044PartitionInfoDefaults struct {
	// Raw value for DefMemPerCPU or DefMemPerNode
	MemoryPerCpu *int64 `json:"memory_per_cpu,omitempty"`
	PartitionMemoryPerCpu *V0044Uint64NoValStruct `json:"partition_memory_per_cpu,omitempty"`
	PartitionMemoryPerNode *V0044Uint64NoValStruct `json:"partition_memory_per_node,omitempty"`
	Time *V0044Uint32NoValStruct `json:"time,omitempty"`
	// JobDefaults - Comma-separated list of job default values (this field is only used to set new defaults)
	Job *string `json:"job,omitempty"`
}

// NewV0044PartitionInfoDefaults instantiates a new V0044PartitionInfoDefaults object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044PartitionInfoDefaults() *V0044PartitionInfoDefaults {
	this := V0044PartitionInfoDefaults{}
	return &this
}

// NewV0044PartitionInfoDefaultsWithDefaults instantiates a new V0044PartitionInfoDefaults object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044PartitionInfoDefaultsWithDefaults() *V0044PartitionInfoDefaults {
	this := V0044PartitionInfoDefaults{}
	return &this
}

// GetMemoryPerCpu returns the MemoryPerCpu field value if set, zero value otherwise.
func (o *V0044PartitionInfoDefaults) GetMemoryPerCpu() int64 {
	if o == nil || IsNil(o.MemoryPerCpu) {
		var ret int64
		return ret
	}
	return *o.MemoryPerCpu
}

// GetMemoryPerCpuOk returns a tuple with the MemoryPerCpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044PartitionInfoDefaults) GetMemoryPerCpuOk() (*int64, bool) {
	if o == nil || IsNil(o.MemoryPerCpu) {
		return nil, false
	}
	return o.MemoryPerCpu, true
}

// HasMemoryPerCpu returns a boolean if a field has been set.
func (o *V0044PartitionInfoDefaults) HasMemoryPerCpu() bool {
	if o != nil && !IsNil(o.MemoryPerCpu) {
		return true
	}

	return false
}

// SetMemoryPerCpu gets a reference to the given int64 and assigns it to the MemoryPerCpu field.
func (o *V0044PartitionInfoDefaults) SetMemoryPerCpu(v int64) {
	o.MemoryPerCpu = &v
}

// GetPartitionMemoryPerCpu returns the PartitionMemoryPerCpu field value if set, zero value otherwise.
func (o *V0044PartitionInfoDefaults) GetPartitionMemoryPerCpu() V0044Uint64NoValStruct {
	if o == nil || IsNil(o.PartitionMemoryPerCpu) {
		var ret V0044Uint64NoValStruct
		return ret
	}
	return *o.PartitionMemoryPerCpu
}

// GetPartitionMemoryPerCpuOk returns a tuple with the PartitionMemoryPerCpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044PartitionInfoDefaults) GetPartitionMemoryPerCpuOk() (*V0044Uint64NoValStruct, bool) {
	if o == nil || IsNil(o.PartitionMemoryPerCpu) {
		return nil, false
	}
	return o.PartitionMemoryPerCpu, true
}

// HasPartitionMemoryPerCpu returns a boolean if a field has been set.
func (o *V0044PartitionInfoDefaults) HasPartitionMemoryPerCpu() bool {
	if o != nil && !IsNil(o.PartitionMemoryPerCpu) {
		return true
	}

	return false
}

// SetPartitionMemoryPerCpu gets a reference to the given V0044Uint64NoValStruct and assigns it to the PartitionMemoryPerCpu field.
func (o *V0044PartitionInfoDefaults) SetPartitionMemoryPerCpu(v V0044Uint64NoValStruct) {
	o.PartitionMemoryPerCpu = &v
}

// GetPartitionMemoryPerNode returns the PartitionMemoryPerNode field value if set, zero value otherwise.
func (o *V0044PartitionInfoDefaults) GetPartitionMemoryPerNode() V0044Uint64NoValStruct {
	if o == nil || IsNil(o.PartitionMemoryPerNode) {
		var ret V0044Uint64NoValStruct
		return ret
	}
	return *o.PartitionMemoryPerNode
}

// GetPartitionMemoryPerNodeOk returns a tuple with the PartitionMemoryPerNode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044PartitionInfoDefaults) GetPartitionMemoryPerNodeOk() (*V0044Uint64NoValStruct, bool) {
	if o == nil || IsNil(o.PartitionMemoryPerNode) {
		return nil, false
	}
	return o.PartitionMemoryPerNode, true
}

// HasPartitionMemoryPerNode returns a boolean if a field has been set.
func (o *V0044PartitionInfoDefaults) HasPartitionMemoryPerNode() bool {
	if o != nil && !IsNil(o.PartitionMemoryPerNode) {
		return true
	}

	return false
}

// SetPartitionMemoryPerNode gets a reference to the given V0044Uint64NoValStruct and assigns it to the PartitionMemoryPerNode field.
func (o *V0044PartitionInfoDefaults) SetPartitionMemoryPerNode(v V0044Uint64NoValStruct) {
	o.PartitionMemoryPerNode = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *V0044PartitionInfoDefaults) GetTime() V0044Uint32NoValStruct {
	if o == nil || IsNil(o.Time) {
		var ret V0044Uint32NoValStruct
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044PartitionInfoDefaults) GetTimeOk() (*V0044Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *V0044PartitionInfoDefaults) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given V0044Uint32NoValStruct and assigns it to the Time field.
func (o *V0044PartitionInfoDefaults) SetTime(v V0044Uint32NoValStruct) {
	o.Time = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *V0044PartitionInfoDefaults) GetJob() string {
	if o == nil || IsNil(o.Job) {
		var ret string
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044PartitionInfoDefaults) GetJobOk() (*string, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *V0044PartitionInfoDefaults) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given string and assigns it to the Job field.
func (o *V0044PartitionInfoDefaults) SetJob(v string) {
	o.Job = &v
}

func (o V0044PartitionInfoDefaults) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044PartitionInfoDefaults) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MemoryPerCpu) {
		toSerialize["memory_per_cpu"] = o.MemoryPerCpu
	}
	if !IsNil(o.PartitionMemoryPerCpu) {
		toSerialize["partition_memory_per_cpu"] = o.PartitionMemoryPerCpu
	}
	if !IsNil(o.PartitionMemoryPerNode) {
		toSerialize["partition_memory_per_node"] = o.PartitionMemoryPerNode
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableV0044PartitionInfoDefaults struct {
	value *V0044PartitionInfoDefaults
	isSet bool
}

func (v NullableV0044PartitionInfoDefaults) Get() *V0044PartitionInfoDefaults {
	return v.value
}

func (v *NullableV0044PartitionInfoDefaults) Set(val *V0044PartitionInfoDefaults) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044PartitionInfoDefaults) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044PartitionInfoDefaults) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044PartitionInfoDefaults(val *V0044PartitionInfoDefaults) *NullableV0044PartitionInfoDefaults {
	return &NullableV0044PartitionInfoDefaults{value: val, isSet: true}
}

func (v NullableV0044PartitionInfoDefaults) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044PartitionInfoDefaults) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


