/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0043ReservationDescMsg type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0043ReservationDescMsg{}

// V0043ReservationDescMsg struct for V0043ReservationDescMsg
type V0043ReservationDescMsg struct {
	Accounts []string `json:"accounts,omitempty"`
	// BurstBuffer
	BurstBuffer *string `json:"burst_buffer,omitempty"`
	// Arbitrary string
	Comment *string `json:"comment,omitempty"`
	CoreCount *V0043Uint32NoValStruct `json:"core_count,omitempty"`
	Duration *V0043Uint32NoValStruct `json:"duration,omitempty"`
	EndTime *V0043Uint64NoValStruct `json:"end_time,omitempty"`
	// Requested node features. Multiple values may be \"&\" separated if all features are required (AND operation) or separated by \"|\" if any of the specified features are required (OR operation). Parenthesis are also supported for features to be ANDed together with counts of nodes having the specified features.
	Features *string `json:"features,omitempty"`
	// Flags associated with this reservation. Note, to remove flags use \"NO_\" prefixed flag excluding NO_HOLD_JOBS_AFTER_END
	Flags []string `json:"flags,omitempty"`
	Groups []string `json:"groups,omitempty"`
	Licenses []string `json:"licenses,omitempty"`
	MaxStartDelay *V0043Uint32NoValStruct `json:"max_start_delay,omitempty"`
	// ReservationName
	Name *string `json:"name,omitempty"`
	NodeCount *V0043Uint32NoValStruct `json:"node_count,omitempty"`
	NodeList []string `json:"node_list,omitempty"`
	// Partition used to reserve nodes from. This will attempt to allocate all nodes in the specified partition unless you request fewer resources than are available with core_cnt, node_cnt or tres.
	Partition *string `json:"partition,omitempty"`
	PurgeCompleted *V0043ReservationInfoPurgeCompleted `json:"purge_completed,omitempty"`
	StartTime *V0043Uint64NoValStruct `json:"start_time,omitempty"`
	Tres []V0043Tres `json:"tres,omitempty"`
	Users []string `json:"users,omitempty"`
}

// NewV0043ReservationDescMsg instantiates a new V0043ReservationDescMsg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043ReservationDescMsg() *V0043ReservationDescMsg {
	this := V0043ReservationDescMsg{}
	return &this
}

// NewV0043ReservationDescMsgWithDefaults instantiates a new V0043ReservationDescMsg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043ReservationDescMsgWithDefaults() *V0043ReservationDescMsg {
	this := V0043ReservationDescMsg{}
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetAccounts() []string {
	if o == nil || IsNil(o.Accounts) {
		var ret []string
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetAccountsOk() ([]string, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []string and assigns it to the Accounts field.
func (o *V0043ReservationDescMsg) SetAccounts(v []string) {
	o.Accounts = v
}

// GetBurstBuffer returns the BurstBuffer field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetBurstBuffer() string {
	if o == nil || IsNil(o.BurstBuffer) {
		var ret string
		return ret
	}
	return *o.BurstBuffer
}

// GetBurstBufferOk returns a tuple with the BurstBuffer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetBurstBufferOk() (*string, bool) {
	if o == nil || IsNil(o.BurstBuffer) {
		return nil, false
	}
	return o.BurstBuffer, true
}

// HasBurstBuffer returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasBurstBuffer() bool {
	if o != nil && !IsNil(o.BurstBuffer) {
		return true
	}

	return false
}

// SetBurstBuffer gets a reference to the given string and assigns it to the BurstBuffer field.
func (o *V0043ReservationDescMsg) SetBurstBuffer(v string) {
	o.BurstBuffer = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *V0043ReservationDescMsg) SetComment(v string) {
	o.Comment = &v
}

// GetCoreCount returns the CoreCount field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetCoreCount() V0043Uint32NoValStruct {
	if o == nil || IsNil(o.CoreCount) {
		var ret V0043Uint32NoValStruct
		return ret
	}
	return *o.CoreCount
}

// GetCoreCountOk returns a tuple with the CoreCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetCoreCountOk() (*V0043Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.CoreCount) {
		return nil, false
	}
	return o.CoreCount, true
}

// HasCoreCount returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasCoreCount() bool {
	if o != nil && !IsNil(o.CoreCount) {
		return true
	}

	return false
}

// SetCoreCount gets a reference to the given V0043Uint32NoValStruct and assigns it to the CoreCount field.
func (o *V0043ReservationDescMsg) SetCoreCount(v V0043Uint32NoValStruct) {
	o.CoreCount = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetDuration() V0043Uint32NoValStruct {
	if o == nil || IsNil(o.Duration) {
		var ret V0043Uint32NoValStruct
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetDurationOk() (*V0043Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given V0043Uint32NoValStruct and assigns it to the Duration field.
func (o *V0043ReservationDescMsg) SetDuration(v V0043Uint32NoValStruct) {
	o.Duration = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetEndTime() V0043Uint64NoValStruct {
	if o == nil || IsNil(o.EndTime) {
		var ret V0043Uint64NoValStruct
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetEndTimeOk() (*V0043Uint64NoValStruct, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given V0043Uint64NoValStruct and assigns it to the EndTime field.
func (o *V0043ReservationDescMsg) SetEndTime(v V0043Uint64NoValStruct) {
	o.EndTime = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetFeatures() string {
	if o == nil || IsNil(o.Features) {
		var ret string
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetFeaturesOk() (*string, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given string and assigns it to the Features field.
func (o *V0043ReservationDescMsg) SetFeatures(v string) {
	o.Features = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetFlags() []string {
	if o == nil || IsNil(o.Flags) {
		var ret []string
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetFlagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *V0043ReservationDescMsg) SetFlags(v []string) {
	o.Flags = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetGroups() []string {
	if o == nil || IsNil(o.Groups) {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *V0043ReservationDescMsg) SetGroups(v []string) {
	o.Groups = v
}

// GetLicenses returns the Licenses field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetLicenses() []string {
	if o == nil || IsNil(o.Licenses) {
		var ret []string
		return ret
	}
	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetLicensesOk() ([]string, bool) {
	if o == nil || IsNil(o.Licenses) {
		return nil, false
	}
	return o.Licenses, true
}

// HasLicenses returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasLicenses() bool {
	if o != nil && !IsNil(o.Licenses) {
		return true
	}

	return false
}

// SetLicenses gets a reference to the given []string and assigns it to the Licenses field.
func (o *V0043ReservationDescMsg) SetLicenses(v []string) {
	o.Licenses = v
}

// GetMaxStartDelay returns the MaxStartDelay field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetMaxStartDelay() V0043Uint32NoValStruct {
	if o == nil || IsNil(o.MaxStartDelay) {
		var ret V0043Uint32NoValStruct
		return ret
	}
	return *o.MaxStartDelay
}

// GetMaxStartDelayOk returns a tuple with the MaxStartDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetMaxStartDelayOk() (*V0043Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.MaxStartDelay) {
		return nil, false
	}
	return o.MaxStartDelay, true
}

// HasMaxStartDelay returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasMaxStartDelay() bool {
	if o != nil && !IsNil(o.MaxStartDelay) {
		return true
	}

	return false
}

// SetMaxStartDelay gets a reference to the given V0043Uint32NoValStruct and assigns it to the MaxStartDelay field.
func (o *V0043ReservationDescMsg) SetMaxStartDelay(v V0043Uint32NoValStruct) {
	o.MaxStartDelay = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V0043ReservationDescMsg) SetName(v string) {
	o.Name = &v
}

// GetNodeCount returns the NodeCount field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetNodeCount() V0043Uint32NoValStruct {
	if o == nil || IsNil(o.NodeCount) {
		var ret V0043Uint32NoValStruct
		return ret
	}
	return *o.NodeCount
}

// GetNodeCountOk returns a tuple with the NodeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetNodeCountOk() (*V0043Uint32NoValStruct, bool) {
	if o == nil || IsNil(o.NodeCount) {
		return nil, false
	}
	return o.NodeCount, true
}

// HasNodeCount returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasNodeCount() bool {
	if o != nil && !IsNil(o.NodeCount) {
		return true
	}

	return false
}

// SetNodeCount gets a reference to the given V0043Uint32NoValStruct and assigns it to the NodeCount field.
func (o *V0043ReservationDescMsg) SetNodeCount(v V0043Uint32NoValStruct) {
	o.NodeCount = &v
}

// GetNodeList returns the NodeList field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetNodeList() []string {
	if o == nil || IsNil(o.NodeList) {
		var ret []string
		return ret
	}
	return o.NodeList
}

// GetNodeListOk returns a tuple with the NodeList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetNodeListOk() ([]string, bool) {
	if o == nil || IsNil(o.NodeList) {
		return nil, false
	}
	return o.NodeList, true
}

// HasNodeList returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasNodeList() bool {
	if o != nil && !IsNil(o.NodeList) {
		return true
	}

	return false
}

// SetNodeList gets a reference to the given []string and assigns it to the NodeList field.
func (o *V0043ReservationDescMsg) SetNodeList(v []string) {
	o.NodeList = v
}

// GetPartition returns the Partition field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetPartition() string {
	if o == nil || IsNil(o.Partition) {
		var ret string
		return ret
	}
	return *o.Partition
}

// GetPartitionOk returns a tuple with the Partition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetPartitionOk() (*string, bool) {
	if o == nil || IsNil(o.Partition) {
		return nil, false
	}
	return o.Partition, true
}

// HasPartition returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasPartition() bool {
	if o != nil && !IsNil(o.Partition) {
		return true
	}

	return false
}

// SetPartition gets a reference to the given string and assigns it to the Partition field.
func (o *V0043ReservationDescMsg) SetPartition(v string) {
	o.Partition = &v
}

// GetPurgeCompleted returns the PurgeCompleted field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetPurgeCompleted() V0043ReservationInfoPurgeCompleted {
	if o == nil || IsNil(o.PurgeCompleted) {
		var ret V0043ReservationInfoPurgeCompleted
		return ret
	}
	return *o.PurgeCompleted
}

// GetPurgeCompletedOk returns a tuple with the PurgeCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetPurgeCompletedOk() (*V0043ReservationInfoPurgeCompleted, bool) {
	if o == nil || IsNil(o.PurgeCompleted) {
		return nil, false
	}
	return o.PurgeCompleted, true
}

// HasPurgeCompleted returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasPurgeCompleted() bool {
	if o != nil && !IsNil(o.PurgeCompleted) {
		return true
	}

	return false
}

// SetPurgeCompleted gets a reference to the given V0043ReservationInfoPurgeCompleted and assigns it to the PurgeCompleted field.
func (o *V0043ReservationDescMsg) SetPurgeCompleted(v V0043ReservationInfoPurgeCompleted) {
	o.PurgeCompleted = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetStartTime() V0043Uint64NoValStruct {
	if o == nil || IsNil(o.StartTime) {
		var ret V0043Uint64NoValStruct
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetStartTimeOk() (*V0043Uint64NoValStruct, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given V0043Uint64NoValStruct and assigns it to the StartTime field.
func (o *V0043ReservationDescMsg) SetStartTime(v V0043Uint64NoValStruct) {
	o.StartTime = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetTres() []V0043Tres {
	if o == nil || IsNil(o.Tres) {
		var ret []V0043Tres
		return ret
	}
	return o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetTresOk() ([]V0043Tres, bool) {
	if o == nil || IsNil(o.Tres) {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasTres() bool {
	if o != nil && !IsNil(o.Tres) {
		return true
	}

	return false
}

// SetTres gets a reference to the given []V0043Tres and assigns it to the Tres field.
func (o *V0043ReservationDescMsg) SetTres(v []V0043Tres) {
	o.Tres = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *V0043ReservationDescMsg) GetUsers() []string {
	if o == nil || IsNil(o.Users) {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043ReservationDescMsg) GetUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *V0043ReservationDescMsg) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *V0043ReservationDescMsg) SetUsers(v []string) {
	o.Users = v
}

func (o V0043ReservationDescMsg) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0043ReservationDescMsg) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	if !IsNil(o.BurstBuffer) {
		toSerialize["burst_buffer"] = o.BurstBuffer
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.CoreCount) {
		toSerialize["core_count"] = o.CoreCount
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.EndTime) {
		toSerialize["end_time"] = o.EndTime
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.Licenses) {
		toSerialize["licenses"] = o.Licenses
	}
	if !IsNil(o.MaxStartDelay) {
		toSerialize["max_start_delay"] = o.MaxStartDelay
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NodeCount) {
		toSerialize["node_count"] = o.NodeCount
	}
	if !IsNil(o.NodeList) {
		toSerialize["node_list"] = o.NodeList
	}
	if !IsNil(o.Partition) {
		toSerialize["partition"] = o.Partition
	}
	if !IsNil(o.PurgeCompleted) {
		toSerialize["purge_completed"] = o.PurgeCompleted
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.Tres) {
		toSerialize["tres"] = o.Tres
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableV0043ReservationDescMsg struct {
	value *V0043ReservationDescMsg
	isSet bool
}

func (v NullableV0043ReservationDescMsg) Get() *V0043ReservationDescMsg {
	return v.value
}

func (v *NullableV0043ReservationDescMsg) Set(val *V0043ReservationDescMsg) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043ReservationDescMsg) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043ReservationDescMsg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043ReservationDescMsg(val *V0043ReservationDescMsg) *NullableV0043ReservationDescMsg {
	return &NullableV0043ReservationDescMsg{value: val, isSet: true}
}

func (v NullableV0043ReservationDescMsg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043ReservationDescMsg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


