/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated{}

// V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated struct for V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated
type V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated struct {
	// Number of cpu seconds allocated
	Seconds *int64 `json:"seconds,omitempty"`
}

// NewV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated instantiates a new V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated() *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated {
	this := V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated{}
	return &this
}

// NewV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocatedWithDefaults instantiates a new V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocatedWithDefaults() *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated {
	this := V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated{}
	return &this
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) GetSeconds() int64 {
	if o == nil || IsNil(o.Seconds) {
		var ret int64
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) GetSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.Seconds) {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) HasSeconds() bool {
	if o != nil && !IsNil(o.Seconds) {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int64 and assigns it to the Seconds field.
func (o *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) SetSeconds(v int64) {
	o.Seconds = &v
}

func (o V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Seconds) {
		toSerialize["seconds"] = o.Seconds
	}
	return toSerialize, nil
}

type NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated struct {
	value *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) Get() *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) Set(val *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated(val *V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) *NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated {
	return &NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInnerAllocated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


